'use strict';
// ═══════════════════════════════════════════════════════════════
// INPUT / INPUT ELEMENT INFO — TEXT. The descriptions shown by inputInfo.js; no logic here. To describe a new input or drop-down choice, add a line:
//   II_FIELDS  [label regex, kind, text]          kind: 's' drop-down, 'c' checkbox / radio, 'n' any other input or button, '' = any. First match wins.
//                                                 "label" = the input's own label (or the card title when it has none); card Enable boxes are 'ENABLE:<card>'.
//   II_OPTIONS [select label regex, choice regex, text]
//   II_IDS     element id -> text (for inputs with no usable label)
// ═══════════════════════════════════════════════════════════════
const II_FIELDS=[
  // ── Household setup
  [/^Single \/ widowed$/,'c','File as a single taxpayer (or a surviving spouse). Uses the single tax brackets, deduction and Medicare IRMAA tiers, and one person\'s inputs.'],
  [/^Married$/,'c','File jointly as a married couple. Uses the married-filing-jointly brackets, deduction and IRMAA tiers, and shows inputs for both spouses. After the first passing the survivor files as single.'],
  [/^Name$/,'n','Display name for this person, used in card titles, chart legends and popups.'],
  [/^Birth year$/,'n','Used to work out current age, the Social Security full retirement age and the RMD start age.'],
  [/^Birth month$/,'n','Used with the birth year for current age (to a fraction of a year) and for age-based start and end dates.'],
  [/^Current age$/,'n','Calculated from birth year and month and today\'s date. Read-only.'],
  // ── General / Expenses / Tax & Optimizations panels
  [/^Inflation rate/,'n','Yearly inflation. Amounts entered as "tracks inflation" grow at this rate, and it is also the Social Security cost-of-living adjustment (COLA). Charts are shown in today\'s dollars.'],
  [/passes at age$/,'n','Age at which this person is assumed to pass away. Their income stops (unless inherited by the spouse), and a surviving spouse files as single from the following year.'],
  [/^Living expenses \(household/,'n','Yearly household living expenses in today\'s dollars, paid from income first, then dividends, then asset sales or IRA withdrawals.'],
  [/^SCGL$/,'n','Suspended Capital-Gain Loss carryforward: a past capital loss that offsets realized capital gains until it is used up. Enter it in today\'s dollars.'],
  [/^Suspended Capital-Gain Loss/,'n','Past capital loss carried forward. It offsets realized long-term gains (and then up to $3,000 of other income) until it is used up.'],
  [/^AUM fee$/,'s','How the advisory / management fee is charged: as a percentage of the AUM balance, or as a fixed dollar amount per year.'],
  [/^AUM fee$/,'n','Fee amount: a percentage of the AUM balance, or dollars per year in today\'s dollars, depending on the mode chosen.'],
  [/^Swap this many years/,'n','How many years before the last passing the Living-expense and IDGT portfolios exchange assets, so the IDGT holds the high-basis assets.'],
  [/^State$/,'s','Which state\'s income tax to model. The state tax is paid as a household expense and is shown as a dashed line on the Total Income Tax chart.'],
  [/^LTC start age$/,'n','Age at which this person starts needing Long Term Care. Care costs begin that year.'],
  [/^LTC cost/,'n','Yearly cost of this person\'s Long Term Care, in today\'s dollars. It can be itemized as a medical deduction above 7.5% of AGI.'],
  [/living expenses \(\$\/yr/,'n','Household living expenses once Long Term Care has started, in today\'s dollars. Replaces the Living expenses amount from then on.'],
  [/^NIIT threshold change: start year/,'n','First year the speculative new Net Investment Income Tax thresholds below apply.'],
  [/^Single filing threshold/,'n','Speculative NIIT threshold for single filers from the start year on, in today\'s dollars.'],
  [/^Married filing threshold/,'n','Speculative NIIT threshold for married couples from the start year on, in today\'s dollars.'],
  // ── Card Enable / Hide / buttons
  [/^ENABLE:SCGL$/,'c','Include the SCGL carryforward in the projection. Your amount is kept when unchecked.'],
  [/^ENABLE:AUM fee$/,'c','Charge the AUM fee on the balances of portfolios marked AUM.'],
  [/^ENABLE:Expense shortfall withdrawal order$/,'c','Use the order below, instead of the built-in one, to decide which assets pay expenses that income and dividends do not cover.'],
  [/^ENABLE:Asset \/ basis swap$/,'c','Model swapping assets between the Living-expense and IDGT portfolios.'],
  [/^ENABLE:State income tax$/,'c','Include state income tax in the projection.'],
  [/^ENABLE:Long Term Care/,'c','Model Long Term Care costs and the change in living expenses once care starts.'],
  [/^ENABLE:Speculative future exemptions/,'c','Test a speculative change to the NIIT thresholds. Not current law; off by default.'],
  [/^ENABLE:Portfolio withdraw$/,'c','Sell from every non-IDGT portfolio each year as much as fits within the chosen LTCG bracket. Off by default.'],
  [/^LTCG bracket to fill$/,'n','How much of each non-IDGT portfolio is sold each year: as much as fits with taxable income staying within this bracket (20% = no limit).'],
  [/^ENABLE:Wage/,'c','Include this person\'s wage / earned income in the projection.'],
  [/^ENABLE:Social Security/,'c','Include this person\'s Social Security benefit in the projection.'],
  [/^ENABLE:Pension/,'c','Include this person\'s pension in the projection.'],
  [/^ENABLE:Pre-tax IRA/,'c','Include this person\'s pre-tax IRA / 401(k) in the projection.'],
  [/^ENABLE:Roth IRA/,'c','Include this person\'s Roth IRA in the projection.'],
  [/^ENABLE:Portfolio$/,'c','Include this brokerage portfolio in the projection.'],
  [/^ENABLE:Rental$/,'c','Include this rental property in the projection.'],
  [/^ENABLE:Annuity$/,'c','Include this annuity in the projection.'],
  [/^ENABLE:Real estate$/,'c','Include this property in the projection.'],
  [/^Hide$/,'c','Collapses this card or section to save space. Hidden data is still used in the projection and charts if it is enabled.'],
  [/^view IRMAA as tax$/,'c','Counts the Medicare IRMAA surcharge as part of tax on the Total Income Tax chart, so the bars show tax plus IRMAA.'],
  [/^Chart Element Info$/,'c','When checked, hovering a chart describes the chart element under the cursor instead of showing the usual values.'],
  [/^Input Element Info$/,'c','When checked, hovering an input describes it, and each choice in a drop-down menu shows its own description.'],
  [/^Popup Details$/,'c','Adds the line-by-line breakdown to the chart hover popups.'],
  [/^＋ Add/,'','Add another one of these to this person.'],
  [/^Remove/,'','Remove this one from the plan.'],
  [/Rescale$/,'','Refit this chart\'s vertical scale (and horizontal scale where it applies) to the current data.'],
  // ── Wage / pension / generic amounts
  [/^Annual amount/,'n','Yearly amount in today\'s dollars.'],
  [/^Start$/,'n','Age at which this starts, used when "Custom age" is chosen.'],
  [/^End$/,'n','Age at which this ends, used when "Custom age" is chosen.'],
  [/^Start$/,'s','When this starts: now, at a specific age, or (for an IRA) at the RMD age.'],
  [/^End$/,'s','When this ends: at a specific age, or at the person\'s passing.'],
  [/^(Annual change|Credited growth)/,'s','How the amount changes each year in real (today\'s-dollar) terms: no growth, in step with inflation, inflation plus or minus a percentage, or a custom yearly percentage.'],
  [/^(Annual change|Credited growth)/,'n','Percentage used by the selected annual-change option (a spread over inflation, or the custom yearly rate).'],
  [/^Inherited by spouse$/,'c','If this person passes first, the surviving spouse receives this and it continues to count as household income or assets.'],
  [/^Joint owned with spouse/,'c','Held jointly: if the owner passes first the spouse keeps it. If unchecked, it is gone when its owner passes. Its cost basis steps up to value at the first passing of either spouse.'],
  // ── Social Security
  [/^Already started collecting/,'c','Check if benefits have already begun. You then enter the current monthly amount instead of the PIA and claiming age.'],
  [/^Current monthly benefit/,'n','The monthly Social Security benefit you receive now, in today\'s dollars.'],
  [/^PIA at FRA/,'n','Primary Insurance Amount: your monthly benefit if you claim at full retirement age, from your Social Security statement.'],
  [/^Full retirement age/,'n','Age at which you get 100% of your PIA. It is set from the birth year; claiming earlier reduces the benefit and later increases it.'],
  [/^Starts Social Security at age/,'n','Age at which benefits are claimed (62–70). Earlier means smaller monthly checks; later means larger ones.'],
  // ── Brokerage
  [/^Portfolio type$/,'s','Living expense & income portfolios pay expenses and reinvest as needed. An IDGT is a separate trust portfolio held outside the estate.'],
  [/^Portfolio name$/,'n','Name used for this portfolio in the cards and charts.'],
  [/^Start balance/,'n','Current value of the portfolio, in today\'s dollars.'],
  [/^Cost basis \(% of start balance\)/,'n','What you paid, as a percent of the balance. Used to work out realized capital gains when assets are sold. Blank means no unrealized gain.'],
  [/^Annual ODIV yield/,'n','Ordinary dividend yield: yearly dividends as a percent of the balance. The qualified share is set below.'],
  [/^QDIV as % of ODIV/,'n','Part of the dividends that are qualified, taxed at the lower long-term capital-gain rates. The rest are taxed as ordinary income.'],
  [/^Tax-exempt yield/,'n','Yearly tax-exempt income (e.g. municipal-bond interest) as a percent of the balance. Not taxed, but counted for Social Security taxation and Medicare IRMAA.'],
  [/^Foreign asset %/,'n','Percent of the portfolio held in foreign assets, which pay foreign tax that can earn a credit.'],
  [/^Foreign tax credit/,'n','Foreign tax withheld as a percent of the foreign assets, taken as a credit against federal income tax.'],
  [/^AUM \(/,'c','This portfolio\'s balance counts toward the AUM balance on which the household AUM fee (Expenses panel) is charged.'],
  [/^Pay expenses/,'c','This portfolio may be sold to pay household expenses.'],
  // ── Real estate
  [/^Property name$/,'n','Name used for this property in the cards and charts.'],
  [/^Value \(today/,'n','Current market value, in today\'s dollars.'],
  [/^Cost basis \(today/,'n','What you paid plus improvements, used to compute the gain when sold. Blank means no unrealized gain.'],
  [/^Exemption per owner/,'n','Gain excluded from tax per owner when the property is sold (e.g. the home-sale exclusion), in today\'s dollars.'],
  [/^Sell$/,'s','When the property is sold: never, when long term care starts, at the last passing, or at a chosen age. Proceeds move to a portfolio.'],
  [/^Sell when the owner reaches age/,'n','Age of the owner at which the property is sold.'],
  [/^Move value and cost basis to/,'s','The portfolio that receives the sale value and its cost basis.'],
  // ── Rental
  [/^Rental name$/,'n','Name used for this rental in the cards and charts.'],
  [/^Taxable annual amount/,'n','Yearly rental income in today\'s dollars, net of depreciation (Schedule E). Taxed as ordinary income.'],
  [/^Annual depreciation/,'n','Non-cash depreciation. It is cash to the household but not taxed. Fixed in dollars, so it shrinks in today\'s dollars.'],
  // ── Annuity
  [/^Annuity name$/,'n','Name used for this annuity in the cards and charts.'],
  [/^Account value/,'n','Current account value of the annuity, in today\'s dollars.'],
  [/^Premium paid/,'n','What was paid into the annuity, which comes back tax-free. Blank means the account value.'],
  [/^Annual payout$/,'s','Whether the annuity pays a fixed dollar amount each year or a percentage of the account value.'],
  [/^Payout % of account value/,'n','Each year\'s payout as a percent of that year\'s account value.'],
  [/^Fixed annual payout/,'n','Fixed yearly payout in dollars. Not adjusted for inflation.'],
  [/^Payout tax treatment$/,'s','How payouts are taxed: gain first, an exclusion ratio, fully taxable, or tax-exempt.'],
  [/^Tax-exempt % of each payout/,'n','Percent of each payout and of the passing benefit that is not taxed. Payouts still count toward MAGI and Social Security taxation.'],
  [/^Passing benefit/,'s','What the annuity pays heirs at the contract\'s end (passing): a fixed amount, the initial value, or the account value then.'],
  [/^Fixed passing benefit/,'n','Fixed dollar amount paid to heirs at passing. Not adjusted for inflation.'],
  // ── IRA / Roth
  [/^Current balance/,'n','Current account balance, in today\'s dollars.'],
  [/^Annual Roth conversion$/,'s','How much to convert from the pre-tax IRA to the Roth IRA each year: a fixed dollar amount, or as much as fits below chosen tax and IRMAA brackets.'],
  [/^Annual Roth conversion$/,'n','Dollars converted from the pre-tax IRA to the Roth IRA each year, in today\'s dollars. The converted amount is taxed as ordinary income.'],
  [/^Ordinary income tax bracket$/,'n','Conversions stop before taxable ordinary income would go into a bracket above this rate.'],
  [/^IRMAA bracket/,'n','Conversions stop before MAGI would reach the chosen Medicare IRMAA surcharge tier.'],
  [/^Conversion start$/,'s','When Roth conversions begin.'],
  [/^Conversion start$/,'n','Age at which Roth conversions begin.'],
  [/^Itemized deductions exceed/,'n','Conversions begin the first year itemized deductions (Long Term Care above 7.5% of AGI) exceed this amount.'],
  [/^IRA stretch/,'c','Heirs keep the account growing and take it all within 10 years after the passing, instead of all at once.']
];

// ── Descriptions of the choices in a drop-down: [select label regex, option text regex, text]. First match wins.
const II_OPTIONS=[
  [/^(Annual change|Credited growth)/,/^Fixed \$/,'The amount stays the same in dollars, so it shrinks in today\'s dollars as inflation rises.'],
  [/^(Annual change|Credited growth)/,/^Tracks inflation/,'The amount grows with inflation, so it stays constant in today\'s dollars.'],
  [/^(Annual change|Credited growth)/,/^Inflation/,'Grows at inflation plus or minus the percentage you enter. Positive grows faster than inflation, negative slower.'],
  [/^(Annual change|Credited growth)/,/^Custom/,'Grows at a yearly percentage you enter, ignoring inflation.'],
  [/^Start$/,/^Now/,'Starts today.'],
  [/^Start$/,/^RMD age/,'Starts at the required minimum distribution age set by the birth year.'],
  [/^Start$/,/^Custom age/,'Starts at the age you enter.'],
  [/^End$/,/^Passing/,'Ends when this person passes.'],
  [/^End$/,/^Custom age/,'Ends at the age you enter.'],
  [/^Portfolio type$/,/^Living/,'Pays living expenses and income, reinvests dividends, and can be sold as needed. May carry the AUM fee.'],
  [/^Portfolio type$/,/^IDGT/,'Intentionally Defective Grantor Trust: held outside the estate. It does not pay expenses or reinvest, and is charted separately.'],
  [/^Sell$/,/^Never/,'The property is kept for the whole projection.'],
  [/^Sell$/,/^When the last person starts LTC/,'Sold the year the last remaining person starts Long Term Care.'],
  [/^Sell$/,/^At the last person/,'Sold the year the last person passes.'],
  [/^Sell$/,/^At an age/,'Sold when the owner reaches the age you enter.'],
  [/^Move value and cost basis to/,/^Automatic/,'The sale value and cost basis go to the owner\'s first portfolio.'],
  [/^Move value and cost basis to/,/./,'The sale value and cost basis are added to this portfolio.'],
  [/^Annual payout$/,/^Fixed/,'A fixed dollar amount each year, not adjusted for inflation or COLA.'],
  [/^Annual payout$/,/^%/,'A percentage of that year\'s account value.'],
  [/^Payout tax treatment$/,/^Non-qualified, withdrawals/,'Withdrawals come out gain first (taxed as ordinary income), then the premium, which is tax-free.'],
  [/^Payout tax treatment$/,/^Non-qualified, annuitized/,'Each payout is part tax-free return of premium and part taxable, in a constant ratio (exclusion ratio).'],
  [/^Payout tax treatment$/,/^Qualified/,'Annuity held in an IRA or other qualified plan: every payout is fully taxable.'],
  [/^Payout tax treatment$/,/^Tax-exempt/,'A percentage of each payout is not taxed.'],
  [/^Passing benefit/,/^Fixed/,'Heirs receive a fixed dollar amount, not adjusted for inflation.'],
  [/^Passing benefit/,/^Initial/,'Heirs receive the original account value, not adjusted for inflation.'],
  [/^Passing benefit/,/^Account value/,'Heirs receive whatever the account value is at the passing.'],
  [/^Annual Roth conversion$/,/^\$\/yr/,'Convert a fixed dollar amount each year, in today\'s dollars.'],
  [/^Annual Roth conversion$/,/^Below IRMAA/,'Each year convert as much as fits below both the chosen ordinary income tax bracket and the chosen IRMAA tier.'],
  [/^Conversion start$/,/^RMD start/,'Conversions begin when required minimum distributions begin.'],
  [/^Conversion start$/,/^Now/,'Conversions begin this year.'],
  [/^Conversion start$/,/^Custom age/,'Conversions begin at the age you choose.'],
  [/^Conversion start$/,/^When tax bracket/,'Conversions begin the first year taxable ordinary income falls below the bracket you choose.'],
  [/^Conversion start$/,/^When itemized/,'Conversions begin the first year itemized deductions exceed the amount you enter.'],
  [/^Conversion start$/,/^When LTC starts/,'Conversions begin the year Long Term Care starts.'],
  [/^AUM fee$/,/^%/,'Fee is a percentage of the AUM balance each year.'],
  [/^AUM fee$/,/^Fixed/,'Fee is a fixed dollar amount per year, in today\'s dollars.'],
  [/^State$/,/^California/,'California brackets (1%–12.3%, plus 1% over $1M); capital gains taxed as ordinary income; Social Security not taxed.'],
  [/^State$/,/^Washington/,'No income tax, but a capital-gains excise tax: 7% above $278,000 of gains and 9.9% on gains above $1M.']
];

// ── Descriptions of inputs that have no usable label (looked up by element id first).
const II_IDS={
  ltcgDevalue:'Haircut on unrealized gain when a portfolio is cashed out before the last passing: the share of the gain assumed lost to capital-gains tax. Display-only; it reduces the asset values charted.',
  ltcgDevalue2:'Same haircut on unrealized gain, applied after the last passing. Display-only.',
  ordDevalue:'Haircut on pre-tax IRA and taxable-annuity value before the last passing: the share assumed lost to ordinary income tax when withdrawn. Display-only.',
  ordDevalue2:'Same haircut on pre-tax IRA and taxable-annuity value, applied after the last passing. Display-only.',
  tipBgSlider:'Sets how light or dark every chart popup is, from a see-through white (left) to a see-through black (right).'
};
