'use strict';
// ═══════════════════════════════════════════════════════════════
// COMPUTE / TAX — ordinary + qualified income tax, taxable Social
// Security (TSS/SST), NIIT, and marginal-rate helpers (spec §9).
// ═══════════════════════════════════════════════════════════════
function calcOrdTax(ti,brackets){
  if(ti<=0)return 0;let tax=0,prev=0;
  for(const b of brackets){if(ti<=prev)break;tax+=(Math.min(ti,b.lim)-prev)*b.r;prev=b.lim;}
  return tax;
}
function calcQualTax(ordTI, qualIncome, qdivBrackets){
  if(qualIncome<=0)return 0;
  let tax=0, base=ordTI, rem=qualIncome;
  for(const b of qdivBrackets){
    if(rem<=0)break;
    const avail=Math.max(0,b.lim-base);
    const portion=Math.min(rem,avail);
    tax+=portion*b.r; rem-=portion; base=Math.max(base,b.lim);
  }
  return tax;
}
// Per-tier breakdown of calcQualTax's total, e.g. so a chart can stack the 0/15/20% tiers
// as separate bands instead of one lump sum.
function qualTaxTiers(ordTI, qualIncome, qBrackets){
  const res=[]; let rem=qualIncome, base=ordTI;
  for(const b of qBrackets){
    if(rem<=0){ res.push(0); continue; }
    const avail=Math.max(0,b.lim-base);
    const portion=Math.min(rem,avail);
    res.push(portion*b.r); rem-=portion; base=Math.max(base,b.lim);
  }
  return res;
}
// The statutory provisional-income thresholds ($25k/$34k single, $32k/$44k married) are NOT indexed
// to inflation. Because every figure here is in today's $, they shrink by 1/(1+inflation)^k in year k;
// `f` is that factor (1 in year 0). The bracket/deduction/IRMAA tables ARE indexed, so they stay fixed.
function computeTaxableSS(nonSS,totalSS,filing,f=1){
  const pi=nonSS+0.5*totalSS;
  let tss=0;
  if(filing==='married'){
    if(pi>44000*f)tss=Math.min(6000*f+0.85*(pi-44000*f),0.85*totalSS);
    else if(pi>32000*f)tss=Math.min(0.5*(pi-32000*f),0.5*totalSS);
  } else {
    if(pi>34000*f)tss=Math.min(4500*f+0.85*(pi-34000*f),0.85*totalSS);
    else if(pi>25000*f)tss=Math.min(0.5*(pi-25000*f),0.5*totalSS);
  }
  return{taxableSS:Math.max(0,tss),provisional:pi};
}
// §9.2/9.3: SST = "actual social security tax" — the dollar amount of tax
// generated by including the taxable portion of SS in ordinary income —
// not the taxable-SS dollar amount itself. Computed as the incremental tax
// vs. a hypothetical where none of the household's SS is taxable (holding
// non-SS income, filing status and qualified income fixed).
// marginalRate: the true marginal rate on the next dollar of non-SS ordinary
// income, including the compounding effect — an extra dollar of income can
// push more SS into taxability, which is itself taxed, so this can run
// above the statutory bracket rate.
// `teIncome` (optional) is tax-exempt income: it is not taxed, but it raises provisional income, so it is added in the SS-taxability bump (as are QDIV and LTCG).
// `seniorFn(agi)` (optional) is the enhanced senior deduction as a function of AGI, so the no-SS hypothetical and the marginal-rate
// bump use the deduction that AGI would really earn (it phases out at 6% per eligible person, which shows up in the marginal rate).
function computeSSTAndMarginal(nonSSOrdinary, totalSS, filing, qdiv, ltcg, std, ordBrk, qBrk, actualTotalTax, f=1, seniorFn=null, teIncome=0){
  const ordTInoSS = Math.max(0, nonSSOrdinary-std-(seniorFn?seniorFn(nonSSOrdinary+qdiv+ltcg):0));
  const ordTaxNoSS = calcOrdTax(ordTInoSS, ordBrk);
  const qualTaxNoSS = calcQualTax(ordTInoSS, qdiv+ltcg, qBrk);
  const sst = Math.max(0, actualTotalTax - (ordTaxNoSS+qualTaxNoSS));

  const bump=100; // $100 numerical-derivative step, normalized back to a per-$1 rate
  const {taxableSS:taxSS2,provisional:provM}=computeTaxableSS(nonSSOrdinary+bump+qdiv+ltcg+teIncome, totalSS, filing, f);   // QDIV, LTCG and tax-exempt interest all count toward provisional income
  const ordTI2=Math.max(0, nonSSOrdinary+bump+taxSS2-std-(seniorFn?seniorFn(nonSSOrdinary+bump+taxSS2+qdiv+ltcg):0));
  const tax2=calcOrdTax(ordTI2, ordBrk)+calcQualTax(ordTI2, qdiv+ltcg, qBrk);
  const marginalRate=Math.max(0,(tax2-actualTotalTax)/bump);
  // The hypotheticals' intermediate values are returned too, so the Excel export can show them as cached values next to its live formulas.
  return {sst, marginalRate, sstOrdTI:ordTInoSS, sstTaxNoSS:ordTaxNoSS+qualTaxNoSS, mProv:provM, mTSS:taxSS2, mTI:ordTI2, mTax:tax2};
}
// Enhanced deduction for seniors (Schedule 1-A Part V, lines 31–37). Per eligible individual it is
//   max( 0, $6,000 − 6% × max( 0, MAGI − $75,000 ($150,000 joint) ) ),
// and each eligible person on the return gets that same reduced amount (so two eligible spouses get twice it, and it reaches $0
// at MAGI $250,000 joint). MAGI ≈ AGI. The dollar amounts are fixed by statute (not indexed), so like the SS thresholds they are
// scaled by `f` = 1/(1+inflation)^k to stay in today's $. It does not reduce AGI; it reduces taxable income only.
function computeSeniorDeduction(nEligible, magi, filing, f=1){
  if(!(nEligible>0)) return 0;
  const thresh=(filing==='married'?SENIOR_THRESH_MFJ:SENIOR_THRESH_SGL)*f;
  const each=Math.max(0, SENIOR_DED*f - SENIOR_RATE*Math.max(0, magi-thresh));
  return nEligible*each;
}
// §9.4 NIIT: 3.8% of the lesser of net investment income or MAGI over the threshold.
function computeNIIT(nii, magi, filing, f=1, futureTax, year){
  const useFuture = futureTax && futureTax.enabled && year!=null && year>=Number(futureTax.niitStartYear);
  const thresh = useFuture
    ? Math.max(0, Number(filing==='married'?futureTax.niitMarried:futureTax.niitSingle)||0)
    : (filing==='married'?NIIT_THRESH_MFJ:NIIT_THRESH_SGL)*f;
  const excess=Math.max(0, magi-thresh);
  return NIIT_RATE*Math.min(Math.max(0,nii), excess);
}

// State income tax for the year (today's $). `code` is 'CA' or 'WA' (anything else = 0).
//   p.agi, p.taxableSS  — federal AGI and the taxable Social Security inside it (California excludes Social Security)
//   p.ltcgPortfolio     — realized long-term gain from portfolio sales, net of SCGL, excluding real estate (the Washington base)
//   p.filing, p.nAlive, p.nSenior — filing status, living people, living people aged 65+
//   p.f                 — 1/(1+inflation)^k: the un-indexed statutory $1,000,000 thresholds are deflated by it
// California: tax on (AGI − taxable SS − standard deduction) from the California brackets, + 1% over $1M, − personal and senior credits.
// Washington: 7% / 9.9% capital-gains excise tax on portfolio LTCG above the deduction.
function computeStateTax(code, p){
  if(code==='CA'){
    const married=p.filing==='married';
    const ti=Math.max(0, p.agi-p.taxableSS-(married?CA_STD_MFJ:CA_STD_SGL));
    let tax=calcOrdTax(ti, married?CA_ORD_MFJ:CA_ORD_SGL);
    tax+=CA_MH_RATE*Math.max(0, ti-CA_MH_THRESH*p.f);
    tax-=CA_PERSONAL_CREDIT*p.nAlive+CA_SENIOR_CREDIT*p.nSenior;
    return Math.max(0,tax);
  }
  if(code==='WA'){
    const taxable=Math.max(0, p.ltcgPortfolio-WA_CG_DEDUCTION);
    const t2=WA_CG_TIER2*p.f;
    return WA_CG_RATE*Math.min(taxable,t2)+WA_CG_RATE2*Math.max(0,taxable-t2);
  }
  return 0;
}
