'use strict';
// ═══════════════════════════════════════════════════════════════
// COMPUTE / TAX — ordinary + qualified income tax, taxable Social
// Security (TSS/SST), NIIT, and marginal-rate helpers (spec §9).
// ═══════════════════════════════════════════════════════════════
function calcOrdTax(ti,brackets){
  if(ti<=0)return 0;let tax=0,prev=0;
  for(const b of brackets){if(ti<=prev)break;tax+=(Math.min(ti,b.lim)-prev)*b.r;prev=b.lim;}
  return tax;
}
function calcQualTax(ordTI, qualIncome, qdivBrackets){
  if(qualIncome<=0)return 0;
  let tax=0, base=ordTI, rem=qualIncome;
  for(const b of qdivBrackets){
    if(rem<=0)break;
    const avail=Math.max(0,b.lim-base);
    const portion=Math.min(rem,avail);
    tax+=portion*b.r; rem-=portion; base=Math.max(base,b.lim);
  }
  return tax;
}
// Per-tier breakdown of calcQualTax's total, e.g. so a chart can stack the 0/15/20% tiers
// as separate bands instead of one lump sum.
function qualTaxTiers(ordTI, qualIncome, qBrackets){
  const res=[]; let rem=qualIncome, base=ordTI;
  for(const b of qBrackets){
    if(rem<=0){ res.push(0); continue; }
    const avail=Math.max(0,b.lim-base);
    const portion=Math.min(rem,avail);
    res.push(portion*b.r); rem-=portion; base=Math.max(base,b.lim);
  }
  return res;
}
// The statutory provisional-income thresholds ($25k/$34k single, $32k/$44k married) are NOT indexed
// to inflation. Because every figure here is in today's $, they shrink by 1/(1+inflation)^k in year k;
// `f` is that factor (1 in year 0). The bracket/deduction/IRMAA tables ARE indexed, so they stay fixed.
function computeTaxableSS(nonSS,totalSS,filing,f=1){
  const pi=nonSS+0.5*totalSS;
  let tss=0;
  if(filing==='married'){
    if(pi>44000*f)tss=Math.min(6000*f+0.85*(pi-44000*f),0.85*totalSS);
    else if(pi>32000*f)tss=Math.min(0.5*(pi-32000*f),0.5*totalSS);
  } else {
    if(pi>34000*f)tss=Math.min(4500*f+0.85*(pi-34000*f),0.85*totalSS);
    else if(pi>25000*f)tss=Math.min(0.5*(pi-25000*f),0.5*totalSS);
  }
  return{taxableSS:Math.max(0,tss),provisional:pi};
}
// §9.2/9.3: SST = "actual social security tax" — the dollar amount of tax
// generated by including the taxable portion of SS in ordinary income —
// not the taxable-SS dollar amount itself. Computed as the incremental tax
// vs. a hypothetical where none of the household's SS is taxable (holding
// non-SS income, filing status and qualified income fixed).
// marginalRate: the true marginal rate on the next dollar of non-SS ordinary
// income, including the compounding effect — an extra dollar of income can
// push more SS into taxability, which is itself taxed, so this can run
// above the statutory bracket rate.
function computeSSTAndMarginal(nonSSOrdinary, totalSS, filing, qdiv, ltcg, std, ordBrk, qBrk, actualTotalTax, f=1){
  const ordTInoSS = Math.max(0, nonSSOrdinary-std);
  const ordTaxNoSS = calcOrdTax(ordTInoSS, ordBrk);
  const qualTaxNoSS = calcQualTax(ordTInoSS, qdiv+ltcg, qBrk);
  const sst = Math.max(0, actualTotalTax - (ordTaxNoSS+qualTaxNoSS));

  const bump=100; // $100 numerical-derivative step, normalized back to a per-$1 rate
  const {taxableSS:taxSS2}=computeTaxableSS(nonSSOrdinary+bump, totalSS, filing, f);
  const ordTI2=Math.max(0, nonSSOrdinary+bump+taxSS2-std);
  const tax2=calcOrdTax(ordTI2, ordBrk)+calcQualTax(ordTI2, qdiv+ltcg, qBrk);
  const marginalRate=Math.max(0,(tax2-actualTotalTax)/bump);
  return {sst, marginalRate};
}
// §9.4 NIIT: 3.8% of the lesser of net investment income or MAGI over the threshold.
function computeNIIT(nii, magi, filing, f=1, futureTax, year){
  const useFuture = futureTax && futureTax.enabled && year!=null && year>=Number(futureTax.niitStartYear);
  const thresh = useFuture
    ? Math.max(0, Number(filing==='married'?futureTax.niitMarried:futureTax.niitSingle)||0)
    : (filing==='married'?NIIT_THRESH_MFJ:NIIT_THRESH_SGL)*f;
  const excess=Math.max(0, magi-thresh);
  return NIIT_RATE*Math.min(Math.max(0,nii), excess);
}
