'use strict';
// ═══════════════════════════════════════════════════════════════
// DISPLAY / FORMULAS PAGE — "Formulas" button (next to Reset to
// defaults) opens a new tab documenting every calculation and
// variable, so a user can verify the math independently of the app.
// Reference-data tables are rendered live from js/core/constants.js
// so this page can't silently drift out of sync with the real
// brackets/tiers/tables the app actually computes with.
// ═══════════════════════════════════════════════════════════════

function openFormulasPage(){
  const win = window.open('', '_blank');
  if(!win){ alert('Please allow pop-ups for this page to view the formulas in a new tab.'); return; }
  win.document.write(buildFormulasHtml());
  win.document.close();
}

function fpBracketTable(brackets, rateAsPct){
  let prev=0;
  const rows = brackets.map(b=>{
    const range = b.lim===Infinity ? `over ${fmt(prev)}` : `${fmt(prev)} – ${fmt(b.lim)}`;
    prev = b.lim;
    return `<tr><td>${range}</td><td>${(b.r*100).toFixed(rateAsPct?1:0)}%</td></tr>`;
  }).join('');
  return `<table><thead><tr><th>Taxable amount in this bracket</th><th>Rate</th></tr></thead><tbody>${rows}</tbody></table>`;
}

function fpIrmaaTable(tiers){
  let prev=0;
  const rows = tiers.map(t=>{
    const range = t.magi>=750000||t.magi>=500000 ? `over ${fmt(prev)}` : `${fmt(prev)} – ${fmt(t.magi)}`;
    prev = t.magi;
    return `<tr><td>${t.label}</td><td>${range}</td><td>${fmt(t.surch)}/yr per enrolled person</td></tr>`;
  }).join('');
  return `<table><thead><tr><th>Tier</th><th>MAGI range (2-years-prior)</th><th>Part B+D surcharge</th></tr></thead><tbody>${rows}</tbody></table>`;
}

function fpRmdTable(){
  const ages = Object.keys(RMD_TABLE).map(Number).sort((a,b)=>a-b);
  const cells = ages.map(a=>`<td>${a}<br><span class="fp-muted">${RMD_TABLE[a]}</span></td>`);
  // 10 ages per row so the table stays readable instead of one giant strip.
  let rows='', row=[];
  cells.forEach((c,i)=>{ row.push(c); if(row.length===10||i===cells.length-1){ rows+=`<tr>${row.join('')}</tr>`; row=[]; } });
  return `<table class="fp-rmd"><caption>Age (divisor)</caption><tbody>${rows}</tbody></table>`;
}

// ── Display-equation helpers ("math book" style) ──────────────────────────────
// eq(...) renders each argument as its own centered line; fr(n,d) stacks a fraction; pw(rows) renders a
// piecewise definition (a big left brace, one "value  if condition" row per case). Names are set upright and
// the operators are spaced, so an equation reads like a textbook display rather than a run of prose.
function fpFr(n,d){ return `<span class="fp-fr"><span class="fp-n">${n}</span><span class="fp-d">${d}</span></span>`; }
function fpEq(...lines){ return lines.map(l=>`<div class="fp-eq">${l}</div>`).join(''); }
function fpPw(lhs, rows){
  const r = rows.map(([v,c])=>`<tr><td class="fp-pv">${v}</td><td class="fp-pc">${c}</td></tr>`).join('');
  return `<div class="fp-eq"><span class="fp-lhs">${lhs} =</span><span class="fp-brace"></span><table class="fp-pw"><tbody>${r}</tbody></table></div>`;
}
function fpWhere(text){ return `<p class="fp-where">${text}</p>`; }

function buildFormulasHtml(){
  const glossary = [
    ['SS','Social Security'], ['SSA','Social Security Administration'],
    ['FRA','Full Retirement Age'], ['PIA','Primary Insurance Amount (benefit at FRA)'],
    ['COLA','Cost-of-Living Adjustment'], ['SSSBR','Social Security Spousal Benefit Rule'],
    ['RMD','Required Minimum Distribution'], ['IRA','Individual Retirement Account'],
    ['AGI','Adjusted Gross Income'], ['MAGI','Modified Adjusted Gross Income'],
    ['TI','Taxable Income'], ['TB','Tax Brackets'], ['TT','Total Tax'],
    ['PI','Provisional Income'], ['TSS','Total Social Security income (the benefit itself)'],
    ['SST','Social Security Tax (the tax generated by taxing SS, not the taxable-SS dollar amount)'],
    ['NIIT','Net Investment Income Tax'], ['NII','Net Investment Income'],
    ['ODIV','Ordinary (non-qualified) Dividends'], ['QDIV','Qualified Dividends'],
    ['LTCG','Long-Term Capital Gains'], ['SCGL','Suspended Capital-Gain Loss (carryforward)'],
    ['IDGT','Intentionally Defective Grantor Trust'], ['FTC','Foreign Tax Credit'],
    ['IRMAA','Income-Related Monthly Adjustment Amount (Medicare Part B/D surcharge)']
  ].map(([a,f])=>`<tr><td class="fp-acr">${a}</td><td>${f}</td></tr>`).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Calculation Reference — Retirement Income Planner</title>
<style>
  body{font-family:Georgia,'Times New Roman',serif;max-width:900px;margin:32px auto;padding:0 20px;line-height:1.55;color:#1c1c1c;background:#fdfdfb;}
  h1{font-size:26px;margin-bottom:4px;} h2{font-size:19px;margin-top:38px;border-bottom:1px solid #ccc;padding-bottom:4px;}
  h3{font-size:15px;margin-top:22px;color:#333;}
  table{border-collapse:collapse;margin:10px 0 18px;width:100%;font-size:13.5px;}
  th,td{border:1px solid #ddd;padding:5px 9px;text-align:left;vertical-align:top;}
  th{background:#f2f0ea;} caption{caption-side:top;text-align:left;font-size:11px;color:#777;margin-bottom:4px;}
  .fp-acr{font-weight:700;white-space:nowrap;} .fp-muted{color:#888;font-size:11.5px;}
  .fp-note{background:#f6f4ee;border-left:3px solid #b08a3e;padding:8px 12px;font-size:13px;margin:10px 0;}
  .fp-rmd td{text-align:center;font-size:12.5px;}
  code{background:#f2f0ea;padding:1px 5px;border-radius:3px;font-family:'SF Mono',Consolas,monospace;font-size:12.5px;}
  ul{padding-left:20px;} li{margin-bottom:5px;}
  .fp-src{color:#888;font-size:11.5px;}
  /* display equations */
  .fp-eq{margin:12px 0;text-align:center;font-family:'STIX Two Text','Cambria Math','Times New Roman',Georgia,serif;font-size:17px;line-height:2.1;overflow-x:auto;}
  .fp-eq .fp-lhs{margin-right:6px;}
  .fp-fr{display:inline-block;vertical-align:middle;text-align:center;margin:0 4px;line-height:1.35;}
  .fp-fr .fp-n{display:block;padding:0 5px 2px;border-bottom:1px solid #1c1c1c;}
  .fp-fr .fp-d{display:block;padding:2px 5px 0;}
  .fp-brace{display:inline-block;vertical-align:middle;width:9px;height:4.6em;margin:0 6px 0 2px;border:1.5px solid #1c1c1c;border-right:none;border-radius:9px 0 0 9px;}
  .fp-pw{display:inline-table;vertical-align:middle;border-collapse:collapse;margin:0;width:auto;font-size:inherit;}
  .fp-pw td{border:none;padding:0 0 0 0;text-align:left;line-height:1.7;}
  .fp-pw .fp-pv{padding-right:26px;white-space:nowrap;}
  .fp-pw .fp-pc{font-size:14.5px;color:#333;white-space:nowrap;}
  .fp-where{font-size:13px;color:#444;margin:-4px 0 14px;text-align:center;}
  .fp-item{margin:0 0 4px;}
</style></head>
<body>
<h1>Calculation Reference</h1>
<p class="fp-src">Generated from the running app's own reference data (js/core/constants.js) for tax year ${THIS_YEAR} — if this page and the app ever disagree on a number, that means the app was updated after this tab was opened; reopen it to refresh.</p>

<div class="fp-note">All tax calculations in this app are simplified: every dollar is assumed to be ordinary income unless explicitly modeled as qualified income (QDIV/LTCG). Most real-world deductions and credits beyond the standard deduction and the foreign tax credit modeled here are excluded. All figures are shown in today's dollars.</div>

<h2>Glossary</h2>
<table><thead><tr><th>Acronym</th><th>Full name</th></tr></thead><tbody>${glossary}</tbody></table>

<h2>Reference Data (tax year ${THIS_YEAR})</h2>

<h3>Ordinary income tax brackets — Married Filing Jointly</h3>
${fpBracketTable(MFJ_ORD)}
<h3>Ordinary income tax brackets — Single</h3>
${fpBracketTable(SGL_ORD)}
<p>Standard deduction: <strong>${fmt(STD_MFJ)}</strong> married / <strong>${fmt(STD_SGL)}</strong> single.</p>

<h3>Qualified dividend / long-term capital gains brackets — Married Filing Jointly</h3>
${fpBracketTable(MFJ_QDIV, true)}
<h3>Qualified dividend / long-term capital gains brackets — Single</h3>
${fpBracketTable(SGL_QDIV, true)}

<h3>IRMAA tiers (Medicare Part B/D surcharge) — Married Filing Jointly</h3>
${fpIrmaaTable(IRMAA_MFJ)}
<h3>IRMAA tiers — Single</h3>
${fpIrmaaTable(IRMAA_SGL)}

<h3>Net Investment Income Tax (NIIT)</h3>
<p>Rate: <strong>${(NIIT_RATE*100).toFixed(1)}%</strong>. Exemption threshold (not indexed for inflation under current law):
<strong>${fmt(NIIT_THRESH_MFJ)}</strong> married / <strong>${fmt(NIIT_THRESH_SGL)}</strong> single. These thresholds are deflated
in the projection to reflect that they lose real value over time, since every other figure in the app is shown in today's
dollars. The speculative future-threshold scenario (if enabled) overrides this with a fixed today's-dollar amount from its
configured start year onward.</p>

<h3>IRA Required Minimum Distribution — IRS Uniform Lifetime Table divisor by age</h3>
${fpRmdTable()}
<p class="fp-src">Source: <a href="https://www.fidelity.com/bin-public/060_www_fidelity_com/documents/UniformLifetimeTable.pdf">IRS/Fidelity Uniform Lifetime Table</a>. Ages below 72 use a linear approximation for voluntary early withdrawals.</p>

<h2>Formulas</h2>

<h3>Social Security</h3>
<p><strong>Full Retirement Age (FRA)</strong> by birth year: 65 for 1937 or earlier, rising 2 months per year through 66 (1943–1954), then rising again 2 months per year to 67 (1960 or later).</p>

<p><strong>Own-benefit claiming factor.</strong> Claiming <em>m</em> months before FRA reduces PIA by 5/9% per month for the first 36 months early, then 5/12% per month beyond that:</p>
${fpEq(`Benefit<sub>early</sub> = PIA × [ 1 − ${fpFr('5','9')}% × min(<em>m</em>, 36) − ${fpFr('5','12')}% × max(0, <em>m</em> − 36) ]`)}
<p>Claiming after FRA (up to age 70) adds 8% per year of delay:</p>
${fpEq(`Benefit<sub>delayed</sub> = PIA × [ 1 + 8% × (years past FRA) ]`)}

<p><strong>Spousal-benefit claiming factor.</strong> The spousal benefit (up to 50% of the other spouse's PIA) uses a different early-claim rate — 25/36% per month for the first 36 months early, then 5/12% per month beyond — with no delayed-retirement credit past FRA:</p>
${fpEq(`Spousal = 50% × PIA<sub>other</sub> × [ 1 − ${fpFr('25','36')}% × min(<em>m</em>, 36) − ${fpFr('5','12')}% × max(0, <em>m</em> − 36) ]`)}
<p>Each spouse receives the higher of their own benefit or the spousal amount (SSSBR):</p>
${fpEq(`SS benefit = max( own benefit, Spousal )`)}

<p><strong>Survivor benefit.</strong> When one spouse dies, the survivor's benefit becomes the larger of their own benefit or the deceased's benefit:</p>
${fpEq(`Survivor benefit = max( own benefit, deceased's benefit )`)}

<h3>Required Minimum Distributions</h3>
${fpEq(`RMD = ${fpFr('prior-year IRA balance','Uniform Lifetime Table divisor for the owner\'s age that year')}`)}
<p>RMDs are required starting at age 72, 73, or 75 depending on birth year under current law; an earlier voluntary withdrawal uses the same table with an approximated divisor. After an IRA owner passes, if marked to continue to spouse, the surviving spouse inherits the IRA and continues taking RMDs against their own age.</p>
<p><strong>Pre-tax IRA withdraw</strong> (Roth conversion): a separate, real withdrawal on top of the RMD — a flat today's-dollar amount moved into the linked Roth IRA each year the pre-tax IRA still has a balance, taxed exactly like the RMD as ordinary income.</p>
${fpEq(`Withdraw = min( conversion amount, remaining pre-tax IRA balance )`)}

<h3>Taxable Social Security &amp; Social Security Tax (SST)</h3>
<p>Provisional income is the non-Social-Security ordinary income plus half of total Social Security (TSS):</p>
${fpEq(`PI = non-SS ordinary income + 50% × TSS`)}
<p>Taxable SS is then calculated from PI against the statutory thresholds T<sub>1</sub> and T<sub>2</sub> ($25k / $34k single, $32k / $44k married — not indexed for inflation, so deflated here since everything is shown in today's dollars). For a single filer the base amount is $4,500; for a married couple filing jointly it is $6,000 (deflated the same way):</p>
${fpPw('Taxable SS',[
  ['0','PI ≤ T<sub>1</sub>'],
  ['min( 50% × (PI − T<sub>1</sub>),&ensp;50% × TSS )','T<sub>1</sub> &lt; PI ≤ T<sub>2</sub>'],
  ['min( base + 85% × (PI − T<sub>2</sub>),&ensp;85% × TSS )','PI &gt; T<sub>2</sub>']
])}
<p><strong>SST</strong> is <em>not</em> the taxable-SS dollar amount — it's the incremental tax that including taxable SS actually generates, holding non-SS income, filing status and qualified income fixed:</p>
${fpEq(`SST = TT<sub>actual</sub> − TT<sub>no SS taxed</sub>`)}
<p><strong>Marginal rate / "torpedo effect".</strong> The true marginal rate on the next dollar of ordinary income is a small numerical derivative — add $100 of ordinary income, then re-run the taxable-SS and tax calculations:</p>
${fpEq(`Marginal rate = ${fpFr('Tax(ordinary income + $100) − Tax(ordinary income)','$100')}`)}
<p>Because an extra dollar of income can push more Social Security into taxability — and that newly-taxable SS is itself taxed — this marginal rate can run meaningfully above the statutory bracket rate. This compounding effect is what's meant by the "torpedo effect."</p>

<h3>Total Tax (TT)</h3>
<p>Income is built up in stages:</p>
${fpEq(
  `Ordinary income = wages + pension + rental + IRA RMD + pre-tax IRA withdraw + (ODIV − QDIV)`,
  `AGI = ordinary income + taxable SS + QDIV + LTCG<sub>net of SCGL</sub>`,
  `TI = AGI − standard deduction`
)}
${fpWhere('The standard deduction is the married or single amount, based on that year\'s filing status.')}
<p>Ordinary tax on TI comes from the bracket table above; QDIV and LTCG are taxed separately at their own bracket rates, stacked on top of ordinary TI.</p>

<p><strong>Suspended Capital-Gain Loss (SCGL).</strong> Available SCGL shields realized LTCG dollar-for-dollar, before tax, each year until the pool is exhausted — only the amount left over is taxed:</p>
${fpEq(
  `LTCG<sub>net</sub> = max( 0, LTCG − SCGL<sub>available</sub> )`,
  `SCGL<sub>remaining</sub> = max( 0, SCGL<sub>available</sub> − LTCG )`
)}

<p><strong>Foreign Tax Credit (FTC).</strong> For each brokerage portfolio — always active, independent of that portfolio's AUM box or IDGT flag:</p>
${fpEq(`FTC = portfolio balance × foreign asset % × foreign tax credit %`)}
<p>It is summed across every portfolio and subtracted from the ordinary + qualified tax total (floored at $0) — a nonrefundable credit against regular tax, not against NIIT.</p>

<p><strong>Net Investment Income Tax (NIIT).</strong> 3.8% of the lesser of net investment income or MAGI (~AGI) over the threshold above — calculated on the pre-credit ordinary + qualified tax basis, since the foreign tax credit doesn't offset NIIT:</p>
${fpEq(
  `NII = (ODIV − QDIV) + QDIV + LTCG`,
  `NIIT = 3.8% × min( NII,&ensp;max(0, MAGI − threshold) )`
)}

<p>Putting it together:</p>
${fpEq(`TT = max( 0,&ensp;ordinary tax + qualified tax − FTC ) + NIIT`)}

<h3>Brokerage Portfolios</h3>
<p><strong>Dividends.</strong></p>
${fpEq(
  `ODIV = portfolio balance × ODIV yield %`,
  `QDIV = ODIV × QDIV % of ODIV`
)}

<p><strong>Household expense funding waterfall.</strong> The household's expenses are:</p>
${fpEq(`Expenses = living expenses + IRMAA surcharge + AUM fee + income tax`)}
${fpWhere('Living expenses is a flat today\'s-dollar amount. The IRMAA surcharge and income tax (tax drag, the year\'s Total Tax) are always household expenses. The AUM fee is charged on the portfolios whose AUM box is checked (below); the whole AUM fee is a household expense like the rest, so it is paid only by the portfolios with <em>Pay expenses</em> checked.')}
<p>They are paid in this order: (1) household income (wages, Social Security, pension, rental, IRA RMDs); (2) the dividends (ODIV) of the portfolios with <em>Pay expenses</em> checked, shared pro rata, with any dividend not needed reinvested; (3) selling those portfolios\' assets, shared pro rata to balance, for what is left. A portfolio without <em>Pay expenses</em> (the default) contributes neither dividends nor sales to household expenses and reinvests all its dividends. An IDGT follows the same rule.</p>
${fpEq(
  `Paid by income = min( Expenses, household income )`,
  `Paid by dividends = min( ΣODIV, Expenses − Paid by income )`,
  `Shortfall = Expenses − Paid by income − Paid by dividends`,
  `Reinvested = max( 0, ODIV − dividends used )`
)}

<p><strong>Starting cost basis.</strong> The cost basis is entered as a percentage of the portfolio's start balance; a blank basis is treated as no unrealized gain today (100%):</p>
${fpEq(`basis<sub>0</sub> = basis % × start balance`)}

<p><strong>Realized LTCG</strong> (automatic, for every portfolio). Selling shares to cover the shortfall realizes the portfolio's unrealized-gain share:</p>
${fpEq(
  `gain fraction <em>f</em> = max( 0,&ensp;${fpFr('value − basis','value')} )`,
  `LTCG = Sold × <em>f</em>`
)}
<p><strong>Tax ↔ LTCG circularity.</strong> Income tax is an expense, so selling shares to pay it realizes more LTCG, which raises the tax. The model solves this by fixed-point iteration each year: start from last year's tax, run the waterfall, recompute the tax, and repeat until the tax moves by less than half a cent (at most 30 rounds; typically 6–8):</p>
${fpEq(
  `T<sub>0</sub> = prior-year Total Tax`,
  `T<sub>n+1</sub> = Tax( LTCG( Waterfall( living + IRMAA + AUM fee + T<sub>n</sub> ) ) )`,
  `stop when |T<sub>n+1</sub> − T<sub>n</sub>| &lt; $0.005`
)}
<p>Each extra dollar of tax creates well under a dollar of new tax (only the gain share of a sale is LTCG, taxed at no more than about 24% with NIIT), so the map is a contraction and always converges. The Suspended Capital-Gain Loss (SCGL) pool is drawn down once, after the iteration settles.</p>

<p><strong>Cost basis roll-forward.</strong> Each year:</p>
${fpEq(`basis<sub>next</sub> = ${fpFr('basis − Sold × (1 − <em>f</em>) + Reinvested','1 + inflation')}`)}
<p>Sales remove basis in proportion to cost share, reinvested dividends add basis, and basis erodes with inflation because it is a fixed nominal amount. When the owner passes and the portfolio continues to a surviving spouse, a non-IDGT portfolio's basis steps up to its value (gain becomes $0); an IDGT keeps its original basis. The balance itself is unaffected, since growth is total return. The asset charts report the unrealized gain remaining at the end of the plan.</p>

<p><strong>AUM fee.</strong> The AUM balance is the sum of the start-of-year balances of every enabled, funded brokerage portfolio inside its age range whose AUM box is checked, plus every pre-tax IRA and Roth IRA whose AUM box is checked (while held by the household — not while held by heirs under IRA stretch). The fee is a percentage of it, or a fixed dollar amount:</p>
${fpEq(
  `AUM balance = Σ balance<sub>i</sub> &ensp;(AUM box checked; portfolios, pre-tax IRAs, Roth IRAs)`,
  `AUM fee = AUM balance × fee %&emsp;or&emsp;Fixed $ ÷ (1 + inflation)<sup>k</sup>`,
  `share<sub>i</sub> = AUM fee × ${fpFr('balance<sub>i</sub>','AUM balance')}`
)}
<p>A fixed fee is entered in today\'s dollars for year 0 and held flat in nominal terms, so it shrinks in today\'s dollars as inflation compounds. The fee is split across the AUM accounts pro rata to balance, but it is one household expense: it is paid through the waterfall above, by the portfolios with <em>Pay expenses</em> checked — not by the account it is charged on unless that account also pays expenses.</p>

<p><strong>IRMAA as an expense</strong> (always a household expense):</p>
${fpEq(`IRMAA<sub>household</sub> = surcharge( tier reached by prior-year AGI ) × N<sub>65+</sub>`)}
${fpWhere('N<sub>65+</sub> is the number of living people age 65 or older, and the tier uses this year\'s filing status. Year 0 is $0.')}
<p>The prior-year AGI avoids a circularity (this year's AGI depends on LTCG, which depends on asset sales, which fund this surcharge) and mirrors IRMAA's look-back. The tier table is indexed, so it is used in today's dollars as-is. It is charged once per household and paid through the same income → dividends → sales waterfall as every other expense, so selling shares to cover it can realize LTCG.</p>

<p><strong>Annual balance change.</strong></p>
${fpEq(
  `Δ balance = growth − ( dividends used + shares sold )`
)}
<p>Household income pays expenses first, so a portfolio is only drawn down when income falls short. A portfolio outside its age range just compounds: it pays no dividends and is not sold.</p>

<h3>Today's-Dollar Convention</h3>
<p>Every figure in this app — inputs, intermediate values, and every chart — is expressed in today's dollars. An "Annual change" of <em>Fixed $ (no growth)</em> (worded <em>Fixed $ (no COLA)</em> on the Pension card) actually erodes in real terms by the inflation rate each year; <em>Tracks inflation</em> means 0% real growth; <em>Inflation ± X%</em> and <em>Custom annual %</em> both express a real (today's-dollar) growth rate directly.</p>

<h3>Filing Status</h3>
<p>The moment either spouse has died, filing status becomes Single for every subsequent year — every bracket, the standard deduction, and every IRMAA/NIIT threshold for that year onward uses the Single tables.</p>

<hr style="margin:32px 0;border:none;border-top:1px solid #ddd;">
<p class="fp-src">This page is a snapshot — it does not update if you keep changing inputs in the main app tab. Close and reopen it (via the Formulas button) any time you want a fresh copy.</p>
</body></html>`;
}
