'use strict';
// ═══════════════════════════════════════════════════════════════
// DISPLAY / FORMULAS PAGE — "Formulas" button (next to Reset to
// defaults) opens a new tab documenting every calculation and
// variable, so a user can verify the math independently of the app.
// Reference-data tables are rendered live from js/core/constants.js
// so this page can't silently drift out of sync with the real
// brackets/tiers/tables the app actually computes with.
// ═══════════════════════════════════════════════════════════════

function openFormulasPage(){
  const win = window.open('', '_blank');
  if(!win){ alert('Please allow pop-ups for this page to view the formulas in a new tab.'); return; }
  win.document.write(buildFormulasHtml());
  win.document.close();
}

function fpBracketTable(brackets, rateAsPct){
  let prev=0;
  const rows = brackets.map(b=>{
    const range = b.lim===Infinity ? `over ${fmt(prev)}` : `${fmt(prev)} – ${fmt(b.lim)}`;
    prev = b.lim;
    return `<tr><td>${range}</td><td>${(b.r*100).toFixed(rateAsPct?1:0)}%</td></tr>`;
  }).join('');
  return `<table><thead><tr><th>Taxable amount in this bracket</th><th>Rate</th></tr></thead><tbody>${rows}</tbody></table>`;
}

function fpIrmaaTable(tiers){
  let prev=0;
  const rows = tiers.map(t=>{
    const range = t.magi>=750000||t.magi>=500000 ? `over ${fmt(prev)}` : `${fmt(prev)} – ${fmt(t.magi)}`;
    prev = t.magi;
    return `<tr><td>${t.label}</td><td>${range}</td><td>${fmt(t.surch)}/yr per enrolled person</td></tr>`;
  }).join('');
  return `<table><thead><tr><th>Tier</th><th>MAGI range (2-years-prior)</th><th>Part B+D surcharge</th></tr></thead><tbody>${rows}</tbody></table>`;
}

function fpRmdTable(){
  const ages = Object.keys(RMD_TABLE).map(Number).sort((a,b)=>a-b);
  const cells = ages.map(a=>`<td>${a}<br><span class="fp-muted">${RMD_TABLE[a]}</span></td>`);
  // 10 ages per row so the table stays readable instead of one giant strip.
  let rows='', row=[];
  cells.forEach((c,i)=>{ row.push(c); if(row.length===10||i===cells.length-1){ rows+=`<tr>${row.join('')}</tr>`; row=[]; } });
  return `<table class="fp-rmd"><caption>Age (divisor)</caption><tbody>${rows}</tbody></table>`;
}

function buildFormulasHtml(){
  const glossary = [
    ['SS','Social Security'], ['SSA','Social Security Administration'],
    ['FRA','Full Retirement Age'], ['PIA','Primary Insurance Amount (benefit at FRA)'],
    ['COLA','Cost-of-Living Adjustment'], ['SSSBR','Social Security Spousal Benefit Rule'],
    ['RMD','Required Minimum Distribution'], ['IRA','Individual Retirement Account'],
    ['AGI','Adjusted Gross Income'], ['MAGI','Modified Adjusted Gross Income'],
    ['TI','Taxable Income'], ['TB','Tax Brackets'], ['TT','Total Tax'],
    ['PI','Provisional Income'], ['TSS','Total Social Security income (the benefit itself)'],
    ['SST','Social Security Tax (the tax generated by taxing SS, not the taxable-SS dollar amount)'],
    ['NIIT','Net Investment Income Tax'], ['NII','Net Investment Income'],
    ['ODIV','Ordinary (non-qualified) Dividends'], ['QDIV','Qualified Dividends'],
    ['LTCG','Long-Term Capital Gains'], ['SCGL','Suspended Capital-Gain Loss (carryforward)'],
    ['IDGT','Intentionally Defective Grantor Trust'], ['FTC','Foreign Tax Credit'],
    ['IRMAA','Income-Related Monthly Adjustment Amount (Medicare Part B/D surcharge)']
  ].map(([a,f])=>`<tr><td class="fp-acr">${a}</td><td>${f}</td></tr>`).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Calculation Reference — Retirement Income Planner</title>
<style>
  body{font-family:Georgia,'Times New Roman',serif;max-width:900px;margin:32px auto;padding:0 20px;line-height:1.55;color:#1c1c1c;background:#fdfdfb;}
  h1{font-size:26px;margin-bottom:4px;} h2{font-size:19px;margin-top:38px;border-bottom:1px solid #ccc;padding-bottom:4px;}
  h3{font-size:15px;margin-top:22px;color:#333;}
  table{border-collapse:collapse;margin:10px 0 18px;width:100%;font-size:13.5px;}
  th,td{border:1px solid #ddd;padding:5px 9px;text-align:left;vertical-align:top;}
  th{background:#f2f0ea;} caption{caption-side:top;text-align:left;font-size:11px;color:#777;margin-bottom:4px;}
  .fp-acr{font-weight:700;white-space:nowrap;} .fp-muted{color:#888;font-size:11.5px;}
  .fp-note{background:#f6f4ee;border-left:3px solid #b08a3e;padding:8px 12px;font-size:13px;margin:10px 0;}
  .fp-rmd td{text-align:center;font-size:12.5px;}
  code{background:#f2f0ea;padding:1px 5px;border-radius:3px;font-family:'SF Mono',Consolas,monospace;font-size:12.5px;}
  ul{padding-left:20px;} li{margin-bottom:5px;}
  .fp-src{color:#888;font-size:11.5px;}
</style></head>
<body>
<h1>Calculation Reference</h1>
<p class="fp-src">Generated from the running app's own reference data (js/core/constants.js) for tax year ${THIS_YEAR} — if this page and the app ever disagree on a number, that means the app was updated after this tab was opened; reopen it to refresh.</p>

<div class="fp-note">All tax calculations in this app are simplified: every dollar is assumed to be ordinary income unless explicitly modeled as qualified income (QDIV/LTCG). Most real-world deductions and credits beyond the standard deduction and the foreign tax credit modeled here are excluded. All figures are shown in today's dollars.</div>

<h2>Glossary</h2>
<table><thead><tr><th>Acronym</th><th>Full name</th></tr></thead><tbody>${glossary}</tbody></table>

<h2>Reference Data (tax year ${THIS_YEAR})</h2>

<h3>Ordinary income tax brackets — Married Filing Jointly</h3>
${fpBracketTable(MFJ_ORD)}
<h3>Ordinary income tax brackets — Single</h3>
${fpBracketTable(SGL_ORD)}
<p>Standard deduction: <strong>${fmt(STD_MFJ)}</strong> married / <strong>${fmt(STD_SGL)}</strong> single.</p>

<h3>Qualified dividend / long-term capital gains brackets — Married Filing Jointly</h3>
${fpBracketTable(MFJ_QDIV, true)}
<h3>Qualified dividend / long-term capital gains brackets — Single</h3>
${fpBracketTable(SGL_QDIV, true)}

<h3>IRMAA tiers (Medicare Part B/D surcharge) — Married Filing Jointly</h3>
${fpIrmaaTable(IRMAA_MFJ)}
<h3>IRMAA tiers — Single</h3>
${fpIrmaaTable(IRMAA_SGL)}

<h3>Net Investment Income Tax (NIIT)</h3>
<p>Rate: <strong>${(NIIT_RATE*100).toFixed(1)}%</strong>. Exemption threshold (not indexed for inflation under current law):
<strong>${fmt(NIIT_THRESH_MFJ)}</strong> married / <strong>${fmt(NIIT_THRESH_SGL)}</strong> single. These thresholds are deflated
in the projection to reflect that they lose real value over time, since every other figure in the app is shown in today's
dollars. The speculative future-threshold scenario (if enabled) overrides this with a fixed today's-dollar amount from its
configured start year onward.</p>

<h3>IRA Required Minimum Distribution — IRS Uniform Lifetime Table divisor by age</h3>
${fpRmdTable()}
<p class="fp-src">Source: <a href="https://www.fidelity.com/bin-public/060_www_fidelity_com/documents/UniformLifetimeTable.pdf">IRS/Fidelity Uniform Lifetime Table</a>. Ages below 72 use a linear approximation for voluntary early withdrawals.</p>

<h2>Formulas</h2>

<h3>Social Security</h3>
<ul>
  <li><strong>Full Retirement Age (FRA)</strong> by birth year: 65 for 1937 or earlier, rising 2 months per year through 66 (1943–1954), then rising again 2 months per year to 67 (1960 or later).</li>
  <li><strong>Own-benefit claiming factor:</strong> claiming before FRA reduces PIA by 5/9% per month for the first 36 months early, then 5/12% per month beyond that. Claiming after FRA (up to age 70) adds 8% per year of delay.</li>
  <li><strong>Spousal-benefit claiming factor:</strong> the spousal benefit (up to 50% of the other spouse's PIA) uses a different early-claim rate: 25/36% per month for the first 36 months early, then 5/12% per month beyond — with no delayed-retirement credit past FRA. Each spouse receives the higher of their own benefit or this spousal amount (SSSBR).</li>
  <li><strong>Survivor benefit:</strong> when one spouse dies, the survivor's benefit becomes the larger of their own benefit or the deceased's benefit.</li>
</ul>

<h3>Required Minimum Distributions</h3>
<ul>
  <li><code>Annual RMD = prior-year IRA balance ÷ Uniform Lifetime Table divisor for the owner's age that year</code></li>
  <li>RMDs are required starting at age 72, 73, or 75 depending on birth year under current law; an earlier voluntary withdrawal uses the same table with an approximated divisor.</li>
  <li>After an IRA owner passes, if marked to continue to spouse, the surviving spouse inherits the IRA and continues taking RMDs against their own age.</li>
  <li><strong>Pre-tax IRA withdraw</strong> (Roth conversion): a separate, real withdrawal on top of the RMD — a flat today's-dollar amount moved into the linked Roth IRA each year the pre-tax IRA still has a balance, taxed exactly like the RMD as ordinary income.</li>
</ul>

<h3>Taxable Social Security &amp; Social Security Tax (SST)</h3>
<ul>
  <li><code>Provisional Income (PI) = non-SS ordinary income + 50% × total Social Security (TSS)</code></li>
  <li>Taxable SS is calculated from PI against the statutory thresholds ($25k/$34k single, $32k/$44k married — not indexed for inflation, so deflated here since everything is shown in today's dollars):
    <ul>
      <li>Below the first threshold: $0 taxable.</li>
      <li>Between the two thresholds: up to 50% of the excess over the first threshold (capped at 50% of TSS).</li>
      <li>Above the second threshold: 85% of the excess over it, plus a fixed base amount, capped at 85% of TSS.</li>
    </ul>
  </li>
  <li><strong>SST</strong> is <em>not</em> the taxable-SS dollar amount — it's the incremental tax that including taxable SS actually generates: <code>SST = actual Total Tax − a hypothetical Total Tax computed as if none of the household's SS were taxable</code> (holding non-SS income, filing status and qualified income fixed).</li>
  <li><strong>Marginal rate / "torpedo effect":</strong> the true marginal rate on the next dollar of ordinary income is computed by a small numerical derivative (adding $100 of ordinary income and re-running the taxable-SS and tax calculations). Because an extra dollar of income can push more Social Security into taxability — and that newly-taxable SS is itself taxed — this marginal rate can run meaningfully above the statutory bracket rate. This compounding effect is what's meant by the "torpedo effect."</li>
</ul>

<h3>Total Tax (TT)</h3>
<ul>
  <li><code>Ordinary income = wages + pension + rental + IRA RMD + pre-tax IRA withdraw + (ODIV − QDIV)</code></li>
  <li><code>AGI = ordinary income + taxable SS + QDIV + LTCG (net of SCGL)</code></li>
  <li><code>Taxable Income (TI) = AGI − standard deduction</code> (married or single, based on that year's filing status)</li>
  <li>Ordinary tax on TI via the bracket table above; QDIV/LTCG taxed separately at their own bracket rates, stacked on top of ordinary TI.</li>
  <li><strong>Suspended Capital-Gain Loss (SCGL):</strong> available SCGL shields realized LTCG dollar-for-dollar, before tax, each year until the pool is exhausted — only the amount left over after that is taxed.</li>
  <li><strong>Foreign Tax Credit (FTC):</strong> for each brokerage portfolio, always active — independent of that portfolio's Expenses toggle or IDGT flag: <code>FTC = portfolio balance × foreign asset % × foreign tax credit %</code>. Summed across every portfolio and subtracted from the ordinary+qualified tax total above (floored at $0) — a nonrefundable credit against regular tax, not against NIIT.</li>
  <li><strong>Net Investment Income Tax (NIIT):</strong> 3.8% of the lesser of net investment income (ODIV−QDIV + QDIV + LTCG) or MAGI (~AGI) over the threshold above — calculated on the pre-credit ordinary+qualified tax basis, since the foreign tax credit doesn't offset NIIT.</li>
  <li><code>Total Tax (TT) = max(0, ordinary tax + qualified tax − foreign tax credit) + NIIT</code></li>
</ul>

<h3>Brokerage Portfolios</h3>
<ul>
  <li><code>ODIV (ordinary dividends) = portfolio balance × ODIV yield %</code></li>
  <li><code>QDIV (qualified dividends) = ODIV × QDIV % of ODIV</code></li>
  <li><strong>Portfolio expenses waterfall (when Expenses is on):</strong> a portfolio's expenses are <code>withdrawal + fees + tax drag</code>. They are paid in this order: (1) the household's other income — <code>wages + Social Security + pension + rental + IRA withdrawals/RMDs</code> (a Roth conversion is a transfer, not spendable; income is gross of tax) — shared across non-IDGT portfolios in proportion to their expenses, IDGTs receive none; (2) that portfolio's own dividends (ODIV), with any leftover reinvested; (3) selling shares for any <code>shortfall = max(0, expenses − income share − ODIV)</code>. Only the part not paid from other income leaves the portfolio. Each portfolio's dividends pay only its own expenses.</li>
  <li><strong>Realized LTCG (automatic, when Expenses is on):</strong> selling the shortfall realizes the portfolio's unrealized-gain share: <code>gain fraction = max(0, (value − basis) ÷ value)</code> and <code>LTCG = shortfall × gain fraction</code>. Tax drag in this estimate uses the <em>prior year's</em> total tax (TT), so this year's LTCG doesn't circularly depend on this year's own TT. Enter a cost basis on the portfolio; a blank basis is treated as no unrealized gain today.</li>
  <li><strong>Cost basis:</strong> <code>basis = (basis − shortfall × (1 − gain fraction) + reinvested dividends) ÷ (1 + inflation)</code> each year: sales remove basis in proportion to cost share, reinvested dividends add basis, and basis erodes with inflation because it is a fixed nominal amount. When the owner passes and the portfolio continues to a surviving spouse, a non-IDGT portfolio's basis steps up to its value (gain becomes $0); an IDGT keeps its original basis. Each portfolio's dividends pay only its own outflows. The balance itself is unaffected, since growth is total return. The asset charts report the unrealized gain remaining at the end of the plan.</li>
  <li><code>Annual balance change = growth − (tax drag + fee drag + withdrawal − the part paid by other household income)</code> (tax drag/fee drag/withdrawal/LTCG only apply when that portfolio's Expenses toggle is on). Tax drag is this portfolio's configured % of the household's Total Tax; fee drag is either a % of balance or a fixed today's-dollar amount per year (which shrinks in today's-dollar terms as inflation compounds, since it's held flat in nominal terms).</li>
</ul>

<h3>Today's-Dollar Convention</h3>
<p>Every figure in this app — inputs, intermediate values, and every chart — is expressed in today's dollars. An "Annual change" of <em>Fixed $ (no growth)</em> actually erodes in real terms by the inflation rate each year; <em>Tracks inflation</em> means 0% real growth; <em>Inflation ± X%</em> and <em>Custom annual %</em> both express a real (today's-dollar) growth rate directly.</p>

<h3>Filing Status</h3>
<p>The moment either spouse has died, filing status becomes Single for every subsequent year — every bracket, the standard deduction, and every IRMAA/NIIT threshold for that year onward uses the Single tables.</p>

<hr style="margin:32px 0;border:none;border-top:1px solid #ddd;">
<p class="fp-src">This page is a snapshot — it does not update if you keep changing inputs in the main app tab. Close and reopen it (via the Formulas button) any time you want a fresh copy.</p>
</body></html>`;
}
