'use strict';
// ═══════════════════════════════════════════════════════════════
// DISPLAY / FORMULAS PAGE — "Formulas" button (next to Reset to
// defaults) opens a new tab documenting every calculation and
// variable, so a user can verify the math independently of the app.
// Reference-data tables are rendered live from js/core/constants.js
// so this page can't silently drift out of sync with the real
// brackets/tiers/tables the app actually computes with.
// ═══════════════════════════════════════════════════════════════

function openFormulasPage(){
  const win = window.open('', '_blank');
  if(!win){ alert('Please allow pop-ups for this page to view the formulas in a new tab.'); return; }
  win.document.write(buildFormulasHtml());
  win.document.close();
}

function fpBracketTable(brackets, rateAsPct){
  let prev=0;
  const rows = brackets.map(b=>{
    const range = b.lim===Infinity ? `over ${fmt(prev)}` : `${fmt(prev)} – ${fmt(b.lim)}`;
    prev = b.lim;
    return `<tr><td>${range}</td><td>${(b.r*100).toFixed(rateAsPct?1:0)}%</td></tr>`;
  }).join('');
  return `<table><thead><tr><th>Taxable amount in this bracket</th><th>Rate</th></tr></thead><tbody>${rows}</tbody></table>`;
}

function fpIrmaaTable(tiers){
  let prev=0;
  const rows = tiers.map(t=>{
    const range = t.magi>=750000||t.magi>=500000 ? `over ${fmt(prev)}` : `${fmt(prev)} – ${fmt(t.magi)}`;
    prev = t.magi;
    return `<tr><td>${t.label}</td><td>${range}</td><td>${fmt(t.surch)}/yr per enrolled person</td></tr>`;
  }).join('');
  return `<table><thead><tr><th>Tier</th><th>MAGI range (2-years-prior)</th><th>Part B+D surcharge</th></tr></thead><tbody>${rows}</tbody></table>`;
}

function fpRmdTable(){
  const ages = Object.keys(RMD_TABLE).map(Number).sort((a,b)=>a-b);
  const cells = ages.map(a=>`<td>${a}<br><span class="fp-muted">${RMD_TABLE[a]}</span></td>`);
  // 10 ages per row so the table stays readable instead of one giant strip.
  let rows='', row=[];
  cells.forEach((c,i)=>{ row.push(c); if(row.length===10||i===cells.length-1){ rows+=`<tr>${row.join('')}</tr>`; row=[]; } });
  return `<table class="fp-rmd"><caption>Age (divisor)</caption><tbody>${rows}</tbody></table>`;
}

// ── Display-equation helpers ("math book" style) ──────────────────────────────
// eq(...) renders each argument as its own centered line; fr(n,d) stacks a fraction; pw(rows) renders a
// piecewise definition (a big left brace, one "value  if condition" row per case). Names are set upright and
// the operators are spaced, so an equation reads like a textbook display rather than a run of prose.
function fpFr(n,d){ return `<span class="fp-fr"><span class="fp-n">${n}</span><span class="fp-d">${d}</span></span>`; }
function fpEq(...lines){ return lines.map(l=>`<div class="fp-eq">${l}</div>`).join(''); }
function fpPw(lhs, rows){
  const r = rows.map(([v,c])=>`<tr><td class="fp-pv">${v}</td><td class="fp-pc">${c}</td></tr>`).join('');
  return `<div class="fp-eq"><span class="fp-lhs">${lhs} =</span><span class="fp-brace"></span><table class="fp-pw"><tbody>${r}</tbody></table></div>`;
}
function fpWhere(text){ return `<p class="fp-where">${text}</p>`; }

function buildFormulasHtml(){
  const glossary = [
    ['SS','Social Security'], ['SSA','Social Security Administration'],
    ['FRA','Full Retirement Age'], ['PIA','Primary Insurance Amount (benefit at FRA)'],
    ['COLA','Cost-of-Living Adjustment'], ['SSSBR','Social Security Spousal Benefit Rule'],
    ['RMD','Required Minimum Distribution'], ['IRA','Individual Retirement Account'],
    ['AGI','Adjusted Gross Income'], ['MAGI','Modified Adjusted Gross Income (AGI + tax-exempt income for IRMAA; AGI for the senior deduction)'],
    ['TI','Taxable Income'], ['TB','Tax Brackets'], ['TT','Total Tax'],
    ['PI','Provisional Income'], ['TSS','Total Social Security income (the benefit itself)'],
    ['SST','Social Security Tax (the tax generated by taxing SS, not the taxable-SS dollar amount)'],
    ['NIIT','Net Investment Income Tax'], ['NII','Net Investment Income'],
    ['TE','Tax-Exempt income (e.g. municipal-bond interest: untaxed, but part of household income, provisional income and IRMAA MAGI)'], ['ODIV','Ordinary (non-qualified) Dividends'], ['QDIV','Qualified Dividends'],
    ['LTCG','Long-Term Capital Gains'], ['SCGL','Suspended Capital-Gain Loss (carryforward)'],
    ['IDGT','Intentionally Defective Grantor Trust'], ['LIFO','Last-in, first-out: annuity gain is treated as withdrawn (and taxed) before premium'], ['FTC','Foreign Tax Credit'],
    ['IRMAA','Income-Related Monthly Adjustment Amount (Medicare Part B/D surcharge)']
  ].map(([a,f])=>`<tr><td class="fp-acr">${a}</td><td>${f}</td></tr>`).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Calculation Reference — Retirement Income Planner</title>
<style>
  body{font-family:Georgia,'Times New Roman',serif;max-width:900px;margin:32px auto;padding:0 20px;line-height:1.55;color:#1c1c1c;background:#fdfdfb;}
  h1{font-size:26px;margin-bottom:4px;} h2{font-size:19px;margin-top:38px;border-bottom:1px solid #ccc;padding-bottom:4px;}
  h3{font-size:15px;margin-top:22px;color:#333;}
  table{border-collapse:collapse;margin:10px 0 18px;width:100%;font-size:13.5px;}
  th,td{border:1px solid #ddd;padding:5px 9px;text-align:left;vertical-align:top;}
  th{background:#f2f0ea;} caption{caption-side:top;text-align:left;font-size:11px;color:#777;margin-bottom:4px;}
  .fp-acr{font-weight:700;white-space:nowrap;} .fp-muted{color:#888;font-size:11.5px;}
  .fp-note{background:#f6f4ee;border-left:3px solid #b08a3e;padding:8px 12px;font-size:13px;margin:10px 0;}
  .fp-rmd td{text-align:center;font-size:12.5px;}
  code{background:#f2f0ea;padding:1px 5px;border-radius:3px;font-family:'SF Mono',Consolas,monospace;font-size:12.5px;}
  ul{padding-left:20px;} li{margin-bottom:5px;}
  .fp-src{color:#888;font-size:11.5px;}
  /* display equations */
  .fp-eq{margin:12px 0;text-align:center;font-family:'STIX Two Text','Cambria Math','Times New Roman',Georgia,serif;font-size:17px;line-height:2.1;overflow-x:auto;}
  .fp-eq .fp-lhs{margin-right:6px;}
  .fp-fr{display:inline-block;vertical-align:middle;text-align:center;margin:0 4px;line-height:1.35;}
  .fp-fr .fp-n{display:block;padding:0 5px 2px;border-bottom:1px solid #1c1c1c;}
  .fp-fr .fp-d{display:block;padding:2px 5px 0;}
  .fp-brace{display:inline-block;vertical-align:middle;width:9px;height:4.6em;margin:0 6px 0 2px;border:1.5px solid #1c1c1c;border-right:none;border-radius:9px 0 0 9px;}
  .fp-pw{display:inline-table;vertical-align:middle;border-collapse:collapse;margin:0;width:auto;font-size:inherit;}
  .fp-pw td{border:none;padding:0 0 0 0;text-align:left;line-height:1.7;}
  .fp-pw .fp-pv{padding-right:26px;white-space:nowrap;}
  .fp-pw .fp-pc{font-size:14.5px;color:#333;white-space:nowrap;}
  .fp-where{font-size:13px;color:#444;margin:-4px 0 14px;text-align:center;}
  .fp-item{margin:0 0 4px;}
</style></head>
<body>
<h1>Calculation Reference</h1>
<p class="fp-src">Generated from the running app's own reference data (js/core/constants.js) for tax year ${THIS_YEAR} — if this page and the app ever disagree on a number, that means the app was updated after this tab was opened; reopen it to refresh.</p>

<div class="fp-note">All tax calculations in this app are simplified: every dollar is assumed to be ordinary income unless explicitly modeled as qualified income (QDIV/LTCG). Most real-world deductions and credits beyond the standard deduction and the foreign tax credit modeled here are excluded. All figures are shown in today's dollars.</div>

<h2>Glossary</h2>
<table><thead><tr><th>Acronym</th><th>Full name</th></tr></thead><tbody>${glossary}</tbody></table>

<h2>Reference Data (tax year ${THIS_YEAR})</h2>

<h3>Ordinary income tax brackets — Married Filing Jointly</h3>
${fpBracketTable(MFJ_ORD)}
<h3>Ordinary income tax brackets — Single</h3>
${fpBracketTable(SGL_ORD)}
<p>Standard deduction: <strong>${fmt(STD_MFJ)}</strong> married / <strong>${fmt(STD_SGL)}</strong> single.</p>

<h3>Qualified dividend / long-term capital gains brackets — Married Filing Jointly</h3>
${fpBracketTable(MFJ_QDIV, true)}
<h3>Qualified dividend / long-term capital gains brackets — Single</h3>
${fpBracketTable(SGL_QDIV, true)}

<h3>IRMAA tiers (Medicare Part B/D surcharge) — Married Filing Jointly</h3>
${fpIrmaaTable(IRMAA_MFJ)}
<h3>IRMAA tiers — Single</h3>
${fpIrmaaTable(IRMAA_SGL)}

<h3>Net Investment Income Tax (NIIT)</h3>
<p>Rate: <strong>${(NIIT_RATE*100).toFixed(1)}%</strong>. Exemption threshold (not indexed for inflation under current law):
<strong>${fmt(NIIT_THRESH_MFJ)}</strong> married / <strong>${fmt(NIIT_THRESH_SGL)}</strong> single. These thresholds are deflated
in the projection to reflect that they lose real value over time, since every other figure in the app is shown in today's
dollars. The speculative future-threshold scenario (if enabled) overrides this with a fixed today's-dollar amount from its
configured start year onward.</p>

<h3>IRA Required Minimum Distribution — IRS Uniform Lifetime Table divisor by age</h3>
${fpRmdTable()}
<p class="fp-src">Source: <a href="https://www.fidelity.com/bin-public/060_www_fidelity_com/documents/UniformLifetimeTable.pdf">IRS/Fidelity Uniform Lifetime Table</a>. Ages below 72 use a linear approximation for voluntary early withdrawals; ages above 105 use the age-105 divisor (4.6).</p>

<h2>Formulas</h2>

<h3>Social Security</h3>
<p><strong>Full Retirement Age (FRA)</strong> by birth year: 65 for 1937 or earlier, rising 2 months per year through 66 (1943–1954), then rising again 2 months per year to 67 (1960 or later).</p>

<p><strong>Own-benefit claiming factor.</strong> Claiming <em>m</em> months before FRA reduces PIA by 5/9% per month for the first 36 months early, then 5/12% per month beyond that:</p>
${fpEq(`Benefit<sub>early</sub> = PIA × [ 1 − ${fpFr('5','9')}% × min(<em>m</em>, 36) − ${fpFr('5','12')}% × max(0, <em>m</em> − 36) ]`)}
<p>Claiming after FRA (up to age 70) adds 8% per year of delay:</p>
${fpEq(`Benefit<sub>delayed</sub> = PIA × [ 1 + 8% × (years past FRA) ]`)}

<p><strong>Spousal-benefit claiming factor.</strong> The spousal benefit (up to 50% of the other spouse's PIA) uses a different early-claim rate — 25/36% per month for the first 36 months early, then 5/12% per month beyond — with no delayed-retirement credit past FRA:</p>
${fpEq(`Spousal = 50% × PIA<sub>other</sub> × [ 1 − ${fpFr('25','36')}% × min(<em>m</em>, 36) − ${fpFr('5','12')}% × max(0, <em>m</em> − 36) ]`)}
<p>Each spouse receives the higher of their own benefit or the spousal amount (SSSBR):</p>
${fpEq(`SS benefit = max( own benefit, Spousal )`)}
${fpWhere('This is a simplification of the SSA rule (own benefit + the excess of the spousal amount over own PIA, reduced for early claiming); the two agree when both are claimed at or after FRA. The spousal amount here starts at the spouse\'s own claim age, whether or not the other spouse has filed yet.')}

<p><strong>Survivor benefit.</strong> When one spouse dies, the survivor's benefit becomes the larger of their own benefit or the deceased's benefit:</p>
${fpEq(`Survivor benefit = max( own benefit, deceased's benefit )`)}

<h3>Required Minimum Distributions</h3>
${fpEq(`RMD = ${fpFr('prior-year IRA balance','Uniform Lifetime Table divisor for the owner\'s age that year')}`)}
<p>RMDs are required starting at age 72, 73, or 75 depending on birth year under current law; an earlier voluntary withdrawal uses the same table with an approximated divisor. After an IRA owner passes, if marked to continue to spouse, the surviving spouse inherits the IRA and continues taking RMDs against their own age.</p>
<p><strong>Pre-tax IRA withdraw</strong> (Roth conversion): a separate, real withdrawal on top of the RMD — a flat today's-dollar amount moved into the linked Roth IRA each year the pre-tax IRA still has a balance, taxed exactly like the RMD as ordinary income. It starts at the later of the owner's current age and the <em>Conversion start</em> — by default the <em>RMD start</em>, meaning the pre-tax IRA's own Start age (the RMD age unless that Start is changed), or Now, or a custom age — needs the Roth IRA card to be enabled, and stops when the owner passes. The conversion slider runs from $0 to the pre-tax IRA's starting balance and starts at $0 (no conversion).</p>
${fpEq(
  `Withdraw = min( conversion amount, remaining pre-tax IRA balance )`,
  `Roth balance<sub>next</sub> = ( Roth balance + Withdraw − Roth withdrawn for expenses ) × ( 1 + real growth )`
)}
<p><strong>Conversion below brackets</strong> (the second conversion option): instead of a flat amount, the projection finds the largest conversion <em>c</em> (no more than the balance left after the RMD) that keeps both limits satisfied (each slider means <em>below</em> the chosen bracket; 0 = no conversion, last stop = no limit):</p>
${fpEq(
  `ordinary taxable income( c ) ≤ start of the chosen ordinary bracket (the top of the bracket below it)`,
  `MAGI( c ) &lt; MAGI threshold of the IRMAA line labeled with the chosen Part B % over standard`
)}
${fpWhere('Both measures rise with <em>c</em>, but a bigger conversion also raises taxable Social Security and the tax. The tax is itself an expense that is paid by selling assets, and those sales realize LTCG, which feeds back into MAGI — so the calculation is circular. It is solved by iteration: each trial <em>c</em> runs the full tax ↔ LTCG iteration, and the search over <em>c</em> (false position with bisection safeguards) repeats until the largest <em>c</em> under both limits is found to within a cent. A slider at 0 blocks conversions; a slider at its last stop is no limit (both at no limit = the whole balance converts). The 10% stop is a start of $0, so only the standard deduction is filled. IRMAA uses the MAGI of two years earlier, so the IRMAA limit applies to anyone alive and 63 or older (they will be on Medicare two years later) — it keeps applying through the last years instead of dropping away — and uses the filing status of the latest of the next two years in which someone is alive. If other income already exceeds a limit, nothing is converted that year. With two bracket-mode IRAs the first person converts first, then the second converts what is left.')}

<h3>Taxable Social Security &amp; Social Security Tax (SST)</h3>
<p>Provisional income is all the non-Social-Security income that goes into AGI — ordinary income, qualified dividends and long-term capital gains — plus the tax-exempt income (untaxed, but it still counts here) plus half of total Social Security (TSS):</p>
${fpEq(`PI = non-SS ordinary income + QDIV + LTCG<sub>net of SCGL</sub> + tax-exempt income + 50% × TSS`)}
${fpWhere('Because LTCG comes from the asset sales that pay the year\'s expenses and tax, taxable SS moves with it and is solved inside the same tax ↔ LTCG iteration described under Household expense funding.')}
<p>Taxable SS is then calculated from PI against the statutory thresholds T<sub>1</sub> and T<sub>2</sub> ($25k / $34k single, $32k / $44k married — not indexed for inflation, so deflated here since everything is shown in today's dollars). For a single filer the base amount is $4,500; for a married couple filing jointly it is $6,000 (deflated the same way):</p>
${fpPw('Taxable SS',[
  ['0','PI ≤ T<sub>1</sub>'],
  ['min( 50% × (PI − T<sub>1</sub>),&ensp;50% × TSS )','T<sub>1</sub> &lt; PI ≤ T<sub>2</sub>'],
  ['min( base + 85% × (PI − T<sub>2</sub>),&ensp;85% × TSS )','PI &gt; T<sub>2</sub>']
])}
${fpWhere('The base is applied in full; the IRS uses the smaller of the base and 50% of TSS, so for very small benefits (below about $12,000 married / $9,000 single) taxable SS can be slightly overstated.')}
<p><strong>SST</strong> is <em>not</em> the taxable-SS dollar amount — it's the incremental tax that including taxable SS actually generates, holding non-SS income, filing status and qualified income fixed:</p>
${fpEq(`SST = Tax<sub>actual</sub> − Tax<sub>no SS taxed</sub>`)}
${fpWhere('Tax here is ordinary tax + qualified tax only, before the foreign tax credit and without NIIT, so a change in NIIT or FTC is never counted as tax on Social Security. The marginal rate below uses the same basis.')}
<p><strong>Marginal rate / "torpedo effect".</strong> The true marginal rate on the next dollar of ordinary income is a small numerical derivative — add $100 of ordinary income, then re-run the taxable-SS and tax calculations:</p>
${fpEq(`Marginal rate = ${fpFr('Tax(ordinary income + $100) − Tax(ordinary income)','$100')}`)}
${fpWhere('Each re-run recomputes provisional income (which includes QDIV, LTCG and tax-exempt income) and the enhanced senior deduction at the higher income, so the marginal rate also picks up the extra 6% per eligible person while the senior deduction is phasing out.')}
<p>Because an extra dollar of income can push more Social Security into taxability — and that newly-taxable SS is itself taxed — this marginal rate can run meaningfully above the statutory bracket rate. This compounding effect is what's meant by the "torpedo effect."</p>

<h3>Total Tax (TT)</h3>
<p>Income is built up in stages:</p>
${fpEq(
  `Ordinary income = wages + pension + rental + taxable annuity payouts + IRA RMD + pre-tax IRA withdraw + pre-tax IRA withdraw (for expenses) + (ODIV − QDIV)`,
  `AGI = ordinary income + taxable SS + QDIV + LTCG<sub>net of SCGL</sub>`,
  `TI = AGI − max(standard deduction, itemized deductions) − enhanced senior deduction`
)}
${fpWhere('The standard deduction is the married or single amount, based on that year\'s filing status; itemized deductions are the Long Term Care cost above 7.5% of AGI, and whichever is larger is used. The enhanced senior deduction (next paragraph) is taken on top of either one and lowers taxable income but not AGI. Rental in the ordinary-income line is the taxable rental income as entered (see Rental income and depreciation, below).')}
<p><strong>Enhanced deduction for seniors (Schedule 1-A, Part V).</strong> Under current law (tax years 2025 through 2028 only) each person who is 65 or older by the end of the tax year — for 2025 that means born before January 2, 1961, for 2026 before January 2, 1962, and so on — gets up to $6,000, taken whether or not deductions are itemized. It is reduced by 6% of modified AGI (MAGI, taken as AGI) above $75,000 single / $150,000 married filing jointly, and never below $0. On a joint return each eligible spouse gets the same reduced amount:</p>
${fpEq(
  `Reduced amount = max( 0, $6,000 − 6% × max( 0, MAGI − threshold ) )`,
  `Senior deduction = number of eligible living people × Reduced amount`
)}
${fpWhere('Threshold is $75,000 (single) or $150,000 (married filing jointly) for that year\'s filing status, so it drops to the single amount once one spouse has passed and only the survivor counts. One eligible person reaches $0 at MAGI $175,000 single or $250,000 joint; two eligible spouses each lose the same 6%, so the joint deduction also reaches $0 at $250,000. The $6,000 and both thresholds are fixed by law, not indexed, so like the Social Security thresholds they are scaled by 1/(1+inflation)<sup>k</sup> to stay in today\'s dollars. The model knows birth year and month only, so eligibility is tested as birth year + 65 ≤ tax year (a January 1 birthday exactly 65 years earlier is not picked up). The deduction ends after 2028 unless law changes. Because it depends on AGI, it is solved inside the same tax/LTCG iteration as the rest of the return, and the marginal tax rate reflects the extra 6% per eligible person while the deduction is phasing out. The additional standard deduction for age 65+ is not modeled.')}
<p><strong>Rental income and depreciation.</strong> A person can have any number of rental properties (Add / Remove on the Rental income card); each has its own name, on/off switch, age range, annual change and survivor setting, and the household figures below are the sums over every active property. Each property's annual amount is the taxable rental income (Schedule E net income, already reduced by depreciation). Annual depreciation is a non-cash expense, so it is the same as cash to the household but untaxed: it is added into household income, pays expenses ahead of dividends and asset sales, and any excess income left over is reinvested into the portfolios with <em>Reinvest excess income</em> checked, exactly like the other income:</p>
${fpEq(
  `Taxable rental income = Σ rental amount<sub>property</sub>`,
  `Rental cash income = Σ ( rental amount + depreciation )<sub>property</sub>`,
  `Household income = wages + Social Security + pension + rental cash income + tax-exempt income + IRA RMD`,
  `Depreciation<sub>year k</sub> = annual depreciation ÷ (1 + inflation)<sup>k</sup>`
)}
${fpWhere('Depreciation uses the same age range, enable switch and survivor rule as the rental amount. Straight-line depreciation is a fixed dollar amount, so in today\'s dollars it shrinks with inflation (the same treatment as a fixed-dollar AUM fee). The Annual Household Income chart shows it as its own band, separate from taxable rental income, so the chart\'s taxable bands still add up to roughly AGI. Depreciation recapture on a sale and passive-loss limits are not modeled.')}
<p><strong>Long Term Care (LTC).</strong> Each person's LTC starts when they reach their own LTC start age (and is skipped if they pass before it); their LTC cost (entered in today's $) is an extra household expense for each year they are alive after that, paid by the same funding order as other expenses (household income, then dividends, then asset sales, then pre-tax IRA, then Roth IRA):</p>
${fpEq(`LTC expense = Σ LTC cost<sub>person</sub> &ensp;(each person started and alive)`)}
${fpPw('Living expenses',[
  ['Living expenses','before any LTC has started'],
  ['1st LTC living expenses','after the 1st LTC start'],
  ['2nd LTC living expenses','after the 2nd LTC start']
])}
${fpWhere('Living expenses switch to the 1st LTC amount once the first person\'s LTC has started, and to the 2nd LTC amount once the second person\'s has started. A single person only has the 1st amount. Defaults: single $7,500; married 1st = the original living expenses (it follows that field until edited) and 2nd = $15,000; all in today\'s $ and editable.')}
<p>The LTC cost is also the itemized deduction, limited by the 7.5% of AGI floor and compared with the standard deduction each year:</p>
${fpEq(
  `Itemized = max( 0, LTC expense − 7.5% × AGI )`,
  `Deduction = max( standard deduction, Itemized )`
)}
${fpWhere('AGI includes realized LTCG, which depends on the asset sales that pay the year\'s expenses and tax, so the deduction and the tax are solved together by iteration.')}
<p>Ordinary tax on TI comes from the bracket table above; QDIV and LTCG are taxed separately at their own bracket rates, stacked on top of ordinary TI.</p>

<p><strong>Suspended Capital-Gain Loss (SCGL).</strong> Available SCGL shields realized LTCG dollar-for-dollar, before tax, each year until the pool is exhausted — only the amount left over is taxed:</p>
${fpEq(
  `LTCG<sub>net</sub> = max( 0, LTCG − SCGL<sub>available</sub> )`,
  `SCGL<sub>remaining</sub> = max( 0, SCGL<sub>available</sub> − LTCG )`
)}

<p><strong>Foreign Tax Credit (FTC).</strong> For each brokerage portfolio — always active, independent of that portfolio's AUM box or IDGT flag:</p>
${fpEq(`FTC = portfolio balance × foreign asset % × foreign tax credit %`)}
<p>It is summed across every portfolio and subtracted from the ordinary + qualified tax total (floored at $0) — a nonrefundable credit against regular tax, not against NIIT.</p>

<p><strong>Net Investment Income Tax (NIIT).</strong> 3.8% of the lesser of net investment income or MAGI (~AGI) over the threshold above — calculated on the pre-credit ordinary + qualified tax basis, since the foreign tax credit doesn't offset NIIT:</p>
${fpEq(
  `NII = (ODIV − QDIV) + QDIV + LTCG<sub>net of SCGL</sub> + taxable payouts of non-qualified annuities`,
  `NIIT = 3.8% × min( NII,&ensp;max(0, MAGI − threshold) )`
)}

<p>Putting it together:</p>
${fpEq(`TT = max( 0,&ensp;ordinary tax + qualified tax − FTC ) + NIIT`)}

<h3>Brokerage Portfolios</h3>
<p><strong>Dividends.</strong></p>
${fpEq(
  `ODIV = portfolio balance × ODIV yield %`,
  `QDIV = ODIV × QDIV % of ODIV`
)}
<p><strong>Tax-exempt income.</strong> Each portfolio has a <em>Tax-exempt yield %</em> (default 0), e.g. municipal-bond interest. It is a share of the portfolio's total return that is paid out to the household every year while the portfolio is in its age range. The paid-out amount is untaxed — it is never part of AGI — but it is household income, so it is counted in total household income, pays expenses ahead of dividends and asset sales, and any excess is reinvested into the portfolios with <em>Reinvest excess income</em> checked, like the other income:</p>
${fpEq(
  `Tax-exempt income = portfolio balance × tax-exempt yield %`,
  `balance<sub>next</sub> = balance × ( 1 + real growth ) − dividends used − Sold − Tax-exempt income + Reinvested into portfolio`
)}
${fpWhere('Growth is total return, so, like dividends, the tax-exempt income is carved out of it: paying it out lowers the portfolio balance by the same amount (and it is capped at what the portfolio holds). It does not change cost basis. Unlike ODIV, an unspent amount is not automatically left in the portfolio — it is kept only if some portfolio has Reinvest excess income checked. Tax-exempt income is added to the provisional income used to tax Social Security and to the MAGI used for IRMAA (MAGI = AGI + tax-exempt income), as the tax rules require; it is not part of AGI, taxable income or the senior-deduction MAGI (which is AGI).')}

<p><strong>Household expense funding waterfall.</strong> The household's expenses are:</p>
${fpEq(`Expenses = living expenses + LTC expense + IRMAA surcharge + AUM fee + income tax`)}
${fpWhere('Living expenses is a flat today\'s-dollar amount (it switches to the 1st / 2nd LTC living expenses as each LTC starts). The LTC expense is the sum of the LTC costs (today\'s $) of each person whose LTC has started and who is still living; it is paid like every other expense. The IRMAA surcharge and income tax (tax drag, the year\'s Total Tax) are always household expenses. The AUM fee is charged on the portfolios whose AUM box is checked (below); the whole AUM fee is a household expense like the rest, so it is paid only by <em>Living expense &amp; income</em> portfolios.')}
<p>They are paid in this order: (1) household income (wages, Social Security, pension, rental and its depreciation add-back, tax-exempt income, annuity payouts, IRA RMDs); (2) the dividends (ODIV) of the <em>Living expense &amp; income</em> portfolios, shared pro rata, with any dividend not needed reinvested; (3) selling those portfolios\' assets, shared pro rata to balance; (4) if the portfolios are exhausted, withdrawing from pre-tax IRA, shared pro rata to the IRA balances; (5) then withdrawing from the Roth IRA, shared pro rata to the Roth balances, for whatever is still left. Each brokerage portfolio has a <em>Portfolio type</em>: <em>Living expense &amp; income</em> (the default) pays household expenses and receives excess income; an <em>IDGT</em> contributes neither dividends nor sales to household expenses, receives no excess income and reinvests all its dividends.</p>
${fpEq(
  `Paid by income = min( Expenses, household income )`,
  `Paid by dividends = min( ΣODIV, Expenses − Paid by income )`,
  `Paid by asset sales = min( portfolio balances, Expenses − Paid by income − Paid by dividends )`,
  `Paid by pre-tax IRA = min( pre-tax IRA balances, remaining expenses )`,
  `Paid by Roth IRA = min( Roth IRA balances, remaining expenses )`,
  `Shortfall = Expenses − Paid by income − Paid by dividends − Paid by asset sales − Paid by pre-tax IRA − Paid by Roth IRA`,
  `Reinvested = max( 0, ODIV − dividends used )`
)}

<p><strong>Pre-tax IRA and Roth IRA as last resorts.</strong> Only when household income, dividends and portfolio sales together cannot cover the year\'s expenses, the model withdraws from pre-tax IRA first and then from the Roth IRA. Each step is shared across the people\'s accounts pro rata to balance, and can never exceed what the account holds that year (the start-of-year balance after the RMD; a Roth conversion that year leaves the pre-tax IRA and arrives in the Roth IRA, so it is netted from the one and added to the other). It applies to accounts the household still holds: the owner\'s own account while alive, or an account inherited by the living spouse (not an account held by heirs under IRA stretch). The pre-tax IRA withdraw is ordinary income, taxed like the RMD, so it raises the tax expense and therefore the amount that has to be sold (the same fixed-point iteration below grosses it up). The Roth IRA withdraw is tax-free and does not enter AGI or MAGI; it is shown on the Annual Household Income chart as a tax-exempt band. Neither amount is household cash income, so neither can create excess income. The balances then roll forward as shown. No early-withdrawal penalty or age limit is modeled.</p>
${fpEq(
  `Pre-tax IRA withdraw<sub><em>j</em></sub> = remaining expenses × ${fpFr('(balance<sub><em>j</em></sub> − conversion<sub><em>j</em></sub>)','Σ (balance − conversion)')}&ensp;(never more than the account holds)`,
  `Roth withdrawn<sub><em>j</em></sub> = remaining expenses × ${fpFr('(balance<sub><em>j</em></sub> + conversion<sub><em>j</em></sub>)','Σ (balance + conversion)')}`,
  `pre-tax IRA balance<sub>next</sub> = ( balance − RMD − conversion − Pre-tax IRA withdraw ) × ( 1 + real growth )`,
  `Roth IRA balance<sub>next</sub> = ( balance + conversion − Roth withdrawn ) × ( 1 + real growth )`
)}

<p><strong>Reinvest excess income.</strong> When household income alone covers every expense, the part left over is <em>excess income</em>. It is reinvested at year-end into the <em>Living expense &amp; income</em> portfolios that are inside their age range, shared pro rata to their start-of-year balances. Because excess exists only when income covered all expenses, it never occurs in a year when dividends were used or shares sold. Only household cash income counts (wages, Social Security, pension, rental with its depreciation add-back, tax-exempt income, annuity payouts, IRA RMDs); the Roth-conversion amount is excluded because it moves to the Roth IRA. It is computed after the tax and expense calculation settles, so it does not change that year\'s tax. If there is no such portfolio, the excess simply leaves the model.</p>
${fpEq(
  `Excess income = max( 0, household income − Expenses )`,
  `Reinvested into portfolio <em>j</em> = Excess income × ${fpFr('balance<sub><em>j</em></sub>','Σ balance of the Living expense &amp; income portfolios')}`,
  `balance<sub>next</sub> = balance × ( 1 + real growth ) − dividends used − Sold − Tax-exempt income + Reinvested into portfolio`
)}
${fpWhere('Reinvested dividends and reinvested excess income are both after-tax money put in, so both add cost basis (see the roll-forward below). The money goes in at year-end, so it starts earning growth the following year, the same timing as the asset sales it mirrors.')}

<p><strong>Starting cost basis.</strong> The cost basis is entered as a percentage of the portfolio's start balance; a blank basis is treated as no unrealized gain today (100%):</p>
${fpEq(`basis<sub>0</sub> = basis % × start balance`)}

<p><strong>Realized LTCG</strong> (automatic, for every portfolio). Selling shares to cover the shortfall realizes the portfolio's unrealized-gain share:</p>
${fpEq(
  `gain fraction <em>f</em> = max( 0,&ensp;${fpFr('value − basis','value')} )`,
  `LTCG = Sold × <em>f</em>`
)}
<p><strong>Tax ↔ LTCG circularity.</strong> Income tax is an expense, so selling shares to pay it realizes more LTCG, which raises the tax. The model solves this by fixed-point iteration each year: start from last year's tax, run the waterfall, recompute the tax, and repeat until the tax moves by less than half a cent (at most 60 rounds; typically 6–8):</p>
${fpEq(
  `T<sub>0</sub> = prior-year Total Tax`,
  `T<sub>n+1</sub> = Tax( LTCG, IRA withdraw ( Waterfall( living + LTC + IRMAA + AUM fee + T<sub>n</sub> ) ) )`,
  `stop when |T<sub>n+1</sub> − T<sub>n</sub>| &lt; $0.005`
)}
<p>Each extra dollar of tax creates well under a dollar of new tax (only the gain share of a sale is LTCG, taxed at no more than about 24% with NIIT; a pre-tax IRA dollar is taxed at the ordinary rate, plus the Social Security torpedo, which stays below 100%), so the map is a contraction and converges. When pre-tax IRA is being withdrawn it converges more slowly, which is why the cap is 60 rounds. The Suspended Capital-Gain Loss (SCGL) pool is drawn down once, after the iteration settles.</p>

<p><strong>Cost basis roll-forward.</strong> Each year:</p>
${fpEq(`basis<sub>next</sub> = ${fpFr('basis − Sold × (1 − <em>f</em>) + Reinvested dividends + Reinvested excess income','1 + inflation')}`)}
<p>Sales remove basis in proportion to cost share, reinvested dividends and reinvested excess income add basis, and basis erodes with inflation because it is a fixed nominal amount. When the owner passes and the portfolio continues to a surviving spouse, a non-IDGT portfolio's basis steps up to its value (gain becomes $0); an IDGT keeps its original basis. The balance itself is unaffected, since growth is total return. The asset charts report the unrealized gain remaining at the end of the plan.</p>
<p><strong>Asset Value chart withdraw cost (display only).</strong> Two slider pairs shrink the plotted bands toward an after-tax value; they never change the projection. The first pair applies to the years up to the last passing, the second pair to the stretch years after it; all four default to 0%:</p>
${fpEq(
  `brokerage band = balance − LTCG withdraw cost % × unrealized gain`,
  `pre-tax IRA band = balance × ( 1 − ordinary income withdraw cost % )`,
  `annuity band = balance − ordinary income withdraw cost % × taxable part of the balance`,
  `Roth IRA band = balance   (no withdraw cost)`
)}
<p>Because the withdraw cost removes a share of the gain but leaves basis untouched, a 100% LTCG withdraw cost puts the top of the brokerage band exactly at cost basis. The dashed cost-basis line is therefore drawn only in years where the applicable LTCG withdraw cost is 0%; at any LTCG withdraw cost above 0% the line is removed (and so is its legend key).</p>

<p><strong>AUM fee.</strong> The AUM balance is the sum of the start-of-year balances of every enabled, funded brokerage portfolio inside its age range whose AUM box is checked, plus every pre-tax IRA and Roth IRA whose AUM box is checked (while held by the household — not while held by heirs under IRA stretch). The fee is a percentage of it, or a fixed dollar amount:</p>
${fpEq(
  `AUM balance = Σ balance<sub>i</sub> &ensp;(AUM box checked; portfolios, pre-tax IRAs, Roth IRAs)`,
  `AUM fee = AUM balance × fee %&emsp;or&emsp;Fixed $ ÷ (1 + inflation)<sup>k</sup>`,
  `share<sub>i</sub> = AUM fee × ${fpFr('balance<sub>i</sub>','AUM balance')}`
)}
<p>A fixed fee is entered in today\'s dollars for year 0 and held flat in nominal terms, so it shrinks in today\'s dollars as inflation compounds. The fee is split across the AUM accounts pro rata to balance, but it is one household expense: it is paid through the waterfall above, by the portfolios with <em>Pay expenses</em> checked — not by the account it is charged on unless that account also pays expenses.</p>

<p><strong>IRMAA as an expense</strong> (always a household expense):</p>
${fpEq(
  `MAGI = AGI + tax-exempt income`,
  `IRMAA<sub>household</sub> = surcharge( tier reached by MAGI<sub>year − 2</sub> ) × N<sub>65+</sub>`
)}
${fpWhere('N<sub>65+</sub> is the number of living people age 65 or older, and the tier uses this year\'s filing status. Years 0 and 1 are $0 because the model has no MAGI from before the projection starts.')}
<p>Using the MAGI from two years earlier mirrors IRMAA's real 2-year look-back, and it also avoids a circularity (this year's AGI depends on LTCG, which depends on asset sales, which fund this surcharge). The tier table is indexed, so it is used in today's dollars as-is. It is charged once per household and paid through the same funding waterfall (income → dividends → asset sales → pre-tax IRA → Roth IRA) as every other expense, so selling shares to cover it can realize LTCG.</p>

<p><strong>IRMAA on the charts.</strong> The MAGI chart beside Annual Household Income stacks this year's MAGI by source:</p>
${fpEq(
  `MAGI = wages + pension + rental + annuity + IRA withdrawals + Roth conversions + pre-tax IRA withdraw (for expenses) + ODIV + taxable SS + QDIV + LTCG + tax-exempt income`
)}
${fpWhere('Rental counts after depreciation is excluded (it is untaxed) and Social Security counts only its taxable part, split between the two people by benefit share. The dashed lines sit at the IRMAA bracket MAGI amounts for that year\'s filing status. Each is labeled with the Part B premium increase over standard: the standard premium is 25% of the Part B cost and tiers 1–5 are 35%, 50%, 65%, 80% and 85%, so the premium is +40%, +100%, +160%, +220% and +240% higher.')}
<p>The taxable income chart beside it stacks the income the tax brackets are applied to: taxable ordinary income (which the taxable income brackets apply to) with qualified income on top:</p>
${fpEq(
  `Taxable ordinary income = max( 0, ( wages + pension + rental + annuity + IRA withdrawals + Roth conversions + pre-tax IRA withdraw (for expenses) + ODIV + taxable SS ) − deduction )`,
  `Taxable income = taxable ordinary income + QDIV + LTCG<sub>net of SCGL</sub>`
)}
${fpWhere('The deduction is the standard or itemized deduction plus the senior deduction. On the chart it is taken off the bottom of the stack, so each ordinary band is that source\'s taxable part and those bands add up to the taxable ordinary income; QDIV and LTCG are stacked above them, as the qualified tax calculation stacks them. The dashed lines are the taxable income brackets: each marks where an ordinary tax bracket starts and is labeled with the rate that applies above it, so the ordinary part of the stack can be read against them directly (QDIV and LTCG are taxed at their own rates, stacked on top).')}
<p>On the Total Income Tax chart, <em>view IRMAA as tax</em> adds the household IRMAA surcharge paid that year (the expense above) on top of the tax stack, so the dashed line is <em>Total tax + IRMAA surcharge</em>. It is a display option only and never changes the projection.</p>

<p><strong>Annual balance change.</strong></p>
${fpEq(
  `Δ balance = growth − ( dividends used + shares sold )`
)}
<p>Household income pays expenses first, so a portfolio is only drawn down when income falls short. A portfolio outside its age range just compounds: it pays no dividends and is not sold.</p>

<h3>Annuities</h3>
<p>Each person can hold any number of annuities (Add / Remove on the Annuity card). An annuity is simulated year by year in today\'s dollars, independently of the tax calculation. Let <em>V</em> be the start-of-year account value; it is the amount plotted on the Asset Value chart. The credited growth is entered net of all fees, so there is no separate fee.</p>
<p><strong>Payout and account value.</strong> Inside the Start–End age range (a contract that continues to a surviving spouse is judged at the owner\'s last living age):</p>
${fpEq(
  `Fixed $: Payout = min( fixed amount ÷ ( 1 + inflation )<sup>k</sup>, V ) &emsp;(a nominal amount with no inflation / COLA)`,
  `% of value: Payout = min( payout % × V, V )`,
  `V<sub>next</sub> = ( V − Payout ) × ( 1 + real credited growth )`
)}
${fpWhere('Payouts stop when the account is empty. The fixed amount is not adjusted for inflation, so in today\'s dollars it shrinks each year.')}
<p><strong>Tax treatment of each payout</strong> (premium = the premium / cost basis entered, blank = account value; bookkeeping is done in nominal dollars and converted back):</p>
${fpEq(
  `Qualified: Taxable = Payout`,
  `Non-qualified, withdrawals (LIFO): Taxable = min( Payout, max( 0, V − premium remaining ) ); Tax-free = the rest (premium returned)`,
  `Non-qualified, annuitized: Exclusion ratio = min( 1, premium ÷ expected total payout ); Tax-free = min( ratio × Payout, premium remaining )`,
  `Tax-exempt: Tax-free = Payout × tax-exempt %`
)}
${fpWhere('Expected total payout is the sum of the projected payouts, in nominal dollars, up to the owner\'s passing age. Once the premium is fully recovered, the exclusion-ratio treatment makes every further payout fully taxable.')}
<p><strong>Passing benefit</strong> (paid to heirs when the contract ends: the owner\'s passing, or the surviving spouse\'s if it continues to the spouse). It is shown for the legacy and is not household cash flow. Three options, none adjusted for inflation:</p>
${fpEq(
  `Fixed $: Benefit = the fixed amount`,
  `Initial value: Benefit = the account value entered today`,
  `Account value at passing: Benefit = V at the passing`
)}
<p>Its taxable and tax-exempt parts, for every option:</p>
${fpEq(
  `Qualified: Taxable = Benefit`,
  `Non-qualified: Tax-free = min( Benefit, premium remaining ); Taxable = Benefit − Tax-free`,
  `Tax-exempt: Tax-free = Benefit × tax-exempt %`
)}
<p>The taxable part of payouts is ordinary income (it enters AGI and the Ordinary income line above); for non-qualified treatments it is also net investment income for NIIT. The tax-free part is untaxed and never in AGI, but, like tax-exempt portfolio income, it counts toward provisional income (Social Security taxation) and MAGI (IRMAA). Both parts are household cash income, so they pay expenses first in the waterfall above. An annuity ends when its owner passes unless it continues to the spouse; annuities have no step-up and no stretch.</p>

<h3>Today's-Dollar Convention</h3>
<p>Every figure in this app — inputs, intermediate values, and every chart — is expressed in today's dollars. An "Annual change" of <em>Fixed $ (no growth)</em> (worded <em>Fixed $ (no COLA)</em> on the Pension card) actually erodes in real terms by the inflation rate each year; <em>Tracks inflation</em> means 0% real growth; <em>Inflation ± X%</em> means a nominal rate of inflation + X%, so the real rate is X% ÷ (1 + inflation); <em>Custom annual %</em> is a nominal rate, so the real rate is (1 + rate) ÷ (1 + inflation) − 1.</p>

<h3>Filing Status</h3>
<p>The moment either spouse has died, filing status becomes Single for every subsequent year — every bracket, the standard deduction, and every IRMAA/NIIT threshold for that year onward uses the Single tables.</p>

<hr style="margin:32px 0;border:none;border-top:1px solid #ddd;">
<p class="fp-src">This page is a snapshot — it does not update if you keep changing inputs in the main app tab. Close and reopen it (via the Formulas button) any time you want a fresh copy.</p>
</body></html>`;
}
