'use strict';
// ═══════════════════════════════════════════════════════════════
// DISPLAY / TAXABLE SOCIAL SECURITY CHART — TSS vs SST, plus the
// torpedo-effect marginal-rate note (spec §9.2, §9.3).
// ═══════════════════════════════════════════════════════════════
function buildTSSChart(){
  if(typeof Chart==='undefined'||!lastProjection) return;
  const proj=lastProjection, rows=proj.rows;
  if(!rows.length){ document.getElementById('tssChartNote').textContent=''; return; }

  const labels=ageLabelRange(rows[0].age0,chartMaxAge(proj));
  const ages=rows.map(r=>r.age0);
  const tss=alignToAges(ages, rows.map(r=>r.totalSS), labels);
  // §9.2/9.3: SST is the actual dollar tax generated by taxing SS (not the
  // taxable-SS dollar amount) — overlaid on the same $ axis as TSS.
  const sst=alignToAges(ages, rows.map(r=>r.sst), labels);

  const Y_MAX=lockedYMax('tss', ()=>{
    const maxV=Math.max(1,...tss.filter(v=>v!=null));
    return Math.ceil(maxV/5000)*5000+5000;
  });

  const datasets=[
    {label:'Total Social Security (TSS)', data:tss, borderColor:'#3B6FA0', backgroundColor:'transparent', borderWidth:4,
      pointRadius:0, pointHoverRadius:0, pointHitRadius:12, tension:0.25, fill:false, spanGaps:false, yAxisID:'y'},
    {label:'Actual Social Security Tax (SST)', data:sst, borderColor:'#c8860a', backgroundColor:'transparent', borderWidth:4,
      pointRadius:0, pointHoverRadius:0, pointHitRadius:12, tension:0.25, fill:false, spanGaps:false, yAxisID:'y'}
  ];

  const tooltipCallbacks={
    title:items=>{
      const idx=items[0]?.dataIndex;
      const r=idx==null?null:rows[idx];
      return r ? popupPersonAgeLines(proj,r) : [];
    },
    label:()=>null,
    afterBody:items=>{
      const idx=items[0]?.dataIndex;
      const r=idx==null?null:rows[idx];
      if(!r) return [];
      const sstPct=r.totalSS>0?(r.sst/r.totalSS*100):0;
      // §9.3.1: TSS, SST, SST%, top marginal rate always shown; PI is shown only when Show details is on.
      const lines=[mrow('  Total Social Security (TSS)', fmt(r.totalSS)+'/yr')];
      if(showDetails) lines.push(mrow('  Provisional Income (PI)', fmt(r.provisional)+'/yr'));
      lines.push(mrow('  Social Security Tax (SST)', fmt(r.sst)+'/yr'));
      lines.push(mrow('  Social Security Tax Percentage (SST%)', sstPct.toFixed(1)+'%'));
      lines.push(mrow('  Marginal Rate (ordinary income)', (r.marginalRate*100).toFixed(1)+'%'));
      return lines;
    }
  };

  upsertLineChart('tss',{canvasId:'tssChart', labels, datasets, yMax:Y_MAX, tooltip:tooltipCallbacks,
    createOptions:()=>({
      ...CHART_BASE,
      interaction:{mode:'index',intersect:false},
      plugins:{
        legend:{display:false},
        tooltip:{
          enabled:true,
          mode:'index',
          intersect:false,
          ...TIP_STYLE,
          callbacks:justifyTip(tooltipCallbacks)
        }
      },
      scales:{
        x:ageXAxis(ageAxisLabel(proj)),
        y:{min:0,max:Y_MAX,position:'left',title:axisTitle("Social Security — total vs. taxable (today's $)"),
          ticks:{...AXIS_TICKS,callback:v=>'$'+Math.round(v).toLocaleString()},grid:AXIS_GRID}
      }
    })});

  document.getElementById('tssLegend').innerHTML =
    (rows.some(r=>r.totalSS>0.5)?legendItem('Total Social Security (TSS)', '#3B6FA0'):'') +
    (rows.some(r=>r.sst>0.5)?legendItem('Actual Social Security Tax (SST) — overlaid', '#c8860a'):'');
  document.getElementById('tssChartNote').textContent =
    `Both lines share the $ axis. Social Security Tax (SST) is the actual tax generated by taxing Social Security (not the taxable-SS amount) — hover for Provisional Income (PI), Social Security Tax (SST), Social Security Tax Percentage (SST%), and the Top Marginal Rate on the next dollar of ordinary income, which can spike above the statutory bracket as more SS becomes taxable. Filing status switches to Single once the first spouse passes (if married). Axis scale is locked — use Rescale if needed.`;
}

